### ISSUE TITLE
load column data

### ISSUE THREAD

**Issue by Hardcore-fs** [NationalSecurityAgency/ghidra#1497]
**Describe the bug**
Went into equates table, the filter column screen....
then the program caught a "cannot cast" error & threw an exception
`Load column data - Uncaught Exception: java.lang.ClassCastException: class ghidra.program.database.symbol.EquateDB cannot be cast to class java.lang.String (ghidra.program.database.symbol.EquateDB is in unnamed module of loader ghidra.GhidraClassLoader @51016012; java.lang.String is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class ghidra.program.database.symbol.EquateDB cannot be cast to class java.lang.String (ghidra.program.database.symbol.EquateDB is in unnamed module of loader ghidra.GhidraClassLoader @51016012; java.lang.String is in module java.base of loader 'bootstrap')
	at docking.widgets.table.constrainteditor.AutocompletingStringConstraintEditor.handleColumnDataValue(AutocompletingStringConstraintEditor.java:40)
	at docking.widgets.table.constrainteditor.DataLoadingConstraintEditor$LoadDataTask.run(DataLoadingConstraintEditor.java:337)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.BackgroundThreadTaskLauncher.lambda$run$0(BackgroundThreadTaskLauncher.java:50)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`
**To Reproduce**
Went into equates table, the filter column screen....,
 down to "create column filter"
and the error is thrown....
![bam](https://user-images.githubusercontent.com/1309004/73581629-ca81bb80-44c4-11ea-988b-421fa652557f.jpeg)

**Environment (please complete the following information):**
 - OS: osx 10.13.6
 - Java Version: [e.g. 11.0.4]
 - Ghidra Version: [e.g. 9.1.1 public]

**Comment by dragonmacher** [comment]
I cannot reproduce this now.  This may have been fixed by recent changes.

**Comment by Hardcore-fs** [comment]
it was 9.1.1 public......
The error is still there.
could it be becasue I started analysis of file in 9.0.. then upgraded the version

Just re-ran the application same result.

`Load column data - Uncaught Exception: java.lang.ClassCastException: class ghidra.program.database.symbol.EquateDB cannot be cast to class java.lang.String (ghidra.program.database.symbol.EquateDB is in unnamed module of loader ghidra.GhidraClassLoader @51016012; java.lang.String is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class ghidra.program.database.symbol.EquateDB cannot be cast to class java.lang.String (ghidra.program.database.symbol.EquateDB is in unnamed module of loader ghidra.GhidraClassLoader @51016012; java.lang.String is in module java.base of loader 'bootstrap')
	at docking.widgets.table.constrainteditor.AutocompletingStringConstraintEditor.handleColumnDataValue(AutocompletingStringConstraintEditor.java:40)
	at docking.widgets.table.constrainteditor.DataLoadingConstraintEditor$LoadDataTask.run(DataLoadingConstraintEditor.java:337)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.BackgroundThreadTaskLauncher.lambda$run$0(BackgroundThreadTaskLauncher.java:50)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by Hardcore-fs** [comment]
ok.. yet me do a GITpull against latest version then recompile.
