### ISSUE TITLE
GhidraDev cannot set eclipse.pysrc.dir property when PyDev is installed in dropins folder

### ISSUE THREAD

**Issue by matthiaskaiser** [NationalSecurityAgency/ghidra#1707]
Hi!
I'm trying to debug python code with Eclipse.
Although Ghidra 9.1.2 is lunched from Eclipse, breakpoint is set and script is run from Ghidra the breakpoint doesn't get hit:
![image](https://user-images.githubusercontent.com/4790750/78343959-eb858c00-759b-11ea-9b81-4b3fafb9d053.png)

In an older version of ghidra it worked perfectly:
![image](https://user-images.githubusercontent.com/4790750/78344115-31daeb00-759c-11ea-937d-198670640ff2.png)

Also package names aren't resolved properly (e.g from java.lang import IllegalArgumentException)

"askFile" is implemented in class "ghidra.app.script.GhidraScript.askFile(String, String)" but it looks like PyDev isn't aware if it.

I installed:
Eclipse Version: 2018-12 (4.10.0)
Eclipse CDT 8.6.0.201502131403
PyDev for Eclipse	6.3.1.201802272029
GhidraDev	2.1.0.201908140834

Thanks a lot for your help!
Matthias

**Comment by ryanmkurtz** [comment]
If you right click on your Eclipse project and go into properties, does your project's PyDev configuration have a Jython interpreter associated with it?

**Comment by matthiaskaiser** [comment]
yes!

![image](https://user-images.githubusercontent.com/4790750/78364619-0bc64280-75be-11ea-9ba8-545d2477fd8d.png)

![image](https://user-images.githubusercontent.com/4790750/78364662-24365d00-75be-11ea-8d5d-6bb9bd24acad.png)

**Comment by matthiaskaiser** [comment]
![image](https://user-images.githubusercontent.com/4790750/78364716-3adcb400-75be-11ea-8212-6ee4eff683d8.png)

**Comment by matthiaskaiser** [comment]
![image](https://user-images.githubusercontent.com/4790750/78364982-b0488480-75be-11ea-9b21-eb7adc086192.png)

**Comment by ryanmkurtz** [comment]
Hmm, that all looks correct, so I'm a bit stumped.  What happens if you right click on your project, and do GhidraDev -> Link Ghidra, and go through the wizard again?

**Comment by matthiaskaiser** [comment]
![image](https://user-images.githubusercontent.com/4790750/78365508-7b88fd00-75bf-11ea-9c83-47669c4ad7eb.png)

**Comment by matthiaskaiser** [comment]
breakpoint doesn't get hit

**Comment by matthiaskaiser** [comment]
![image](https://user-images.githubusercontent.com/4790750/78366011-2ef1f180-75c0-11ea-97cc-62df092262de.png)

**Comment by ryanmkurtz** [comment]
It looks like now PyDev is aware of the Ghidra classpath though right?

**Comment by matthiaskaiser** [comment]
In method "ghidra.python.GhidraPythonInterpreter.initializePythonPath()" the call to "ghidra.python.PyDevUtils.getPyDevSrcDir()" returns null. Doesn't look right. Can you verify with your version ?

![image](https://user-images.githubusercontent.com/4790750/78367293-1d114e00-75c2-11ea-917a-2b46bcf49bf9.png)

**Comment by ryanmkurtz** [comment]
You are launching your Ghidra from Eclipse, correct?

**Comment by matthiaskaiser** [comment]
yes I do

**Comment by ryanmkurtz** [comment]
When you launch Ghidra from Eclipse, can you check the value of the "eclipse.pysrc.dir" property that Ghidra gets launched with?

**Comment by matthiaskaiser** [comment]
it's null

**Comment by ryanmkurtz** [comment]
But the property exists?

**Comment by matthiaskaiser** [comment]
java.lang.System.getProperty("eclipse.pysrc.dir")  returns null!

**Comment by matthiaskaiser** [comment]
what value does Ghidra expect ?

**Comment by ryanmkurtz** [comment]
Here is the code in the GhidraDev plugin that tries to find the PyDev source directory.  Can you take a look at your filesystem to see if you think it should succeed based on what directories you see?

https://github.com/NationalSecurityAgency/ghidra/blob/bcb825fb029232175625bc85653ec0e810b1252e/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/src/main/java/ghidradev/ghidraprojectcreator/utils/PyDevUtils.java#L141-L161

**Comment by matthiaskaiser** [comment]
Ok. Now we found the problem.

For installing plugins in eclipse you can also put the pluing files into the "dropins" folder ([see here](https://help.eclipse.org/2020-03/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fp2_dropins_format.html)) which I did for pydev.  That's why  it returned "null". 
Thanks a lot for your help!!!

**Comment by ryanmkurtz** [comment]
Great!  Would you mind renaming this ticket to _"GhidraDev cannot set eclipse.pysrc.dir property when PyDev is installed in dropins folder"_ and keeping it open so it can get fixed?

**Comment by matthiaskaiser** [comment]
Ok so I still don't get the breakpoint hit :-( Script runs forever and never returns. Any ideas ?

**Comment by matthiaskaiser** [comment]
Now I get "terminated unknown". 
![image](https://user-images.githubusercontent.com/4790750/78373202-90b75900-75ca-11ea-8a8d-c2df299d5d92.png)
Will try a fresh new install.

**Comment by ryanmkurtz** [comment]
The script not returning implies it's stuck on the breakpoint. Maybe your PyDev debug server is out of sync?  Perhaps restart everything and start fresh?

**Comment by matthiaskaiser** [comment]
Yes. Gonna do that. Will let you know!

**Comment by matthiaskaiser** [comment]
Ok installed latest 
- ECLIPSE for RAP/RCP
- CDT
- PyDev
Runnining with java11.


![image](https://user-images.githubusercontent.com/4790750/78377699-3ae5af80-75d0-11ea-9ecb-27c17c8bb9be.png)

Got green marked line for breakpoint match but eclipse doesn't suspend!

**Comment by matthiaskaiser** [comment]
rerunning the script again shows "unknown":
![image](https://user-images.githubusercontent.com/4790750/78378048-b8112480-75d0-11ea-8ac0-c171a7320dc8.png)

**Comment by bdemick** [comment]
I'm running into the same (or a related) issue on `macOS` with `Eclipse 2020-06 (4.16.0)`, and it's unclear to me exactly what the fix is. I've installed the latest `PyDev (7.6.0)` per the instructions in GhidraDev_README.html, and everything seems to be installed properly (the PyDev plugin has a menu item in Eclipse, and walking through the GhidraDev -> Link Ghidra wizard seems to pick up on PyDev). Looking at the PyDev settings in Eclipse, it appears PyDev is configured to use Ghidra's Jython interpreter.

I then set a breakpoint in the script I want to debug, and then debug with the GhidraScripts configuration, launching Ghidra and invoking the script from the script manager. Script runs in the launched Ghidra instance, but the breakpoint is never captured by the PyDev debugger.

One thing I did notice is that it appears that the GhidraDev extension is installed in the Eclipse installation's dropins folder, but I don't see PyDev in the dropins or plugins folder. Am I missing a configuration step to get this to work properly?

**Comment by ryanmkurtz** [comment]
I've fixed PyDev being installed in the dropins folder not working in #1922 but it hasn't been merged yet.  However, that's not the problem you are experiencing based on what you have reported.

I have opened an issue with PyDev to address the breakpoint not catching in newer versions of PyDev:  https://github.com/fabioz/PyDev.Debugger/issues/171

Unfortunately, it hasn't gotten any attention yet.  The breakpoints work in PyDev 6.3.1 though if you are willing to use an old version.

**Comment by matthiaskaiser** [comment]
Thanks for the update! Using the old version worked for in the past, too!

**Comment by bdemick** [comment]
Thanks for the heads up! I uninstalled latest PyDev, installed 6.3.1, and re-ran `Link Ghidra`, but am still not able to get a breakpoint to hit for a Python script. All I can think of now is that my workflow is incorrect. What's the standard way to debug a Python script from Eclipse? I've been approaching it the same way I debug Java scripts. The steps I'm taking:

1. From the linked project (GhidraScripts), open a script in the editor, set a breakpoint.
2. DebugAs->Ghidra (which launches a new Ghidra instance
3. Display Script Manager, and run the script

At this point, when running a Java script, it pauses on my breakpoint. But for Python, I'm getting nothing.

**Comment by ryanmkurtz** [comment]
Your procedure sounds correct.  Is your PyDev debug server running?

**Comment by bdemick** [comment]
It is, as far as I can tell. Here's my view:

![Screen Shot 2020-07-22 at 2 41 21 PM](https://user-images.githubusercontent.com/3675695/88215351-84164980-cc29-11ea-8e5f-d3cb7b44de83.png)

ghidra_basics.py just runs to completion without hitting the breakpoint set on line 7.

**Comment by ryanmkurtz** [comment]
And you are sure PyDev 6.3.1 is the active PyDev?

**Comment by ryanmkurtz** [comment]
And not installed in the dropins directory?

**Comment by bdemick** [comment]
Looks like 6.3.1 is the active PyDev:
![Screen Shot 2020-07-22 at 2 51 08 PM](https://user-images.githubusercontent.com/3675695/88216327-f5a2c780-cc2a-11ea-8f56-a9aa32265dcc.png)

And I don't see it in dropins:
![Screen Shot 2020-07-22 at 2 51 44 PM](https://user-images.githubusercontent.com/3675695/88216384-04897a00-cc2b-11ea-9ace-d6a024beffa3.png)

Although... I don't see in anywhere in the Eclipse install tree. However I'm not exactly sure where it goes -- I just followed the walkthrough in the GhidraDev readme.

**Comment by ryanmkurtz** [comment]
It should be in the plugins directory somewhere.  It's odd that you only have the one jar in there.

**Comment by bdemick** [comment]
Any other ideas about where Eclipse might be putting it? I've only looked in the application package tree, but I agree that it doesn't seem right to not be copied into dropins or plugins folder by the install process.

**Comment by ryanmkurtz** [comment]
Sorry, I'm out of ideas.  I only know of the plugins and dropins directories.

**Comment by mechgt** [comment]
Is there a workaround or alternate or preferred way to install PyDev to make Python debugging work?  I've been able to recreate the exact same experience as @matthiaskaiser above up until he did something to get the breakpoint to hit.  My breakpoints are never hit.

**Comment by ryanmkurtz** [comment]
Are you using PyDev 6.3.1?

**Comment by mechgt** [comment]
Yes - I downgraded to 6.3.1 based on the above discussion.

![image](https://user-images.githubusercontent.com/25422988/97018628-6fb35700-1560-11eb-8c5e-d6f50495169d.png)

**Comment by ryanmkurtz** [comment]
The original issue was fixed by #1922.  A new ticket has been created for the PyDev debugger not connecting at #2713...we can continue the discussion there.
