### ISSUE TITLE
 Pcode: XML comms: Missing symref attribute in <high> tag

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2360]
**Describe the bug**
loaded an object file with batch loader from an ar archive. ARM:EB:32
decompiler complains 

deleting and reloading didnt help

**Screenshots**
![image](https://user-images.githubusercontent.com/4013370/95809398-f8372980-0d0e-11eb-9ce5-75838d47b607.png)

**Attachments**
ARM:BE:32:v8 (1.103)

ARM mode
address : [000105c8 - 000106d0]
bytes:
```
e9 2d 40 70 e5 9f 50 fc e1 a0 40 00 e5 95 36 1c e1 50 00 03 23 a0 40 00 3a 00 00 01 e1 a0 00 04 e8 bd 80 70 eb 00 06 8c e5 d5 36 40 e3 53 00 00 1a 00 00 21 e2 83 30 01 e5 c5 36 40 eb 00 06 87 e5 95 36 14 e7 93 41 04 e3 54 00 00 0a 00 00 0e eb 00 06 81 e5 d4 30 d4 e3 53 00 00 0a 00 00 1c eb 00 06 7e e2 84 00 d0 e3 a0 10 01 eb 00 06 73 e1 d4 31 b8 e2 13 60 01 0a 00 00 1e e3 a0 2e 15 e1 94 30 b2 e2 83 30 01 e1 84 30 b2 eb 00 06 72 e3 a0 3d 19 e1 95 20 b3 e5 9f 50 68 e3 52 0c 01 0a 00 00 0f eb 00 06 6d e2 85 0e 63 e2 80 00 0c eb 00 06 64 e1 a0 00 04 e8 bd 80 70 eb 00 06 67 e2 85 0e 63 e3 a0 10 01 e2 80 00 0c eb 00 06 5b ea ff ff da e2 83 30 01 e5 c4 30 d4 eb 00 06 5f ea ff ff e2 e2 43 3d 19 e5 c5 36 40 eb 00 06 5b e1 a0 00 04 e8 bd 80 70 e2 84 00 d0 eb 00 06 51 e1 a0 40 06 ea ff ff e0 00 01 20 00
```

**Environment (please complete the following information):**

 - Java Version:  11.0
 - Ghidra Version: October 2020
**Additional context**
in subfloder with many others files

**Comment by mumbel** [comment]
cannot repro with the provided bytes/address using  f7f366b261589a65696c17852812566b9e6659bb

maybe your .sla file got corrupted, I would delete Ghidra/Processors/ARM/data/language/ARM8_be.sla, restart ghidra, and see if the issue persists

**Comment by pabx06** [comment]
interesting . is there some others caching at project levels ?

**Comment by pabx06** [comment]
```
$ md5sum ARM8_be.sla
4842592248245a8637a666eaf34b33ef  ARM8_be.sla
```
closed ghidra & del sla
```
rm ARM8_be.sla
run ghidra && load project & file & new sla get created:
$ md5sum ARM8_be.sla
4842592248245a8637a666eaf34b33ef  ARM8_be.sla

```
here the 
exported program as 'Ghidra Zip File' then gzip it :
[trsockex.o.gzf.gz](https://github.com/NationalSecurityAgency/ghidra/files/5371128/trsockex.o.gzf.gz)

**Comment by pabx06** [comment]
had the same issue occurring on others files from very widely distributed production grade library

**Comment by dev747368** [comment]
@pabx06 Could you also try this using the official 9.1.2 distro from ghidra-sre.org?

**Comment by astrelsky** [comment]
I'm getting this as well in 7357b755f4ac658ac3e630d301160f16070ff842

I think it may be related to some of the references which would be why the bytes for the function didn't reproduce it.

**Comment by pabx06** [comment]
i starts to wonder if it is caused by Analyzers not playing nicely with each other on per settings base

**Comment by caheckman** [comment]
I'm reproducing this.

**Comment by caheckman** [comment]
This is fixed now in master.  Thank you for the submitting this.

**Comment by danra** [comment]
I'm still getting this error on the public 9.2.1 (on a Windows 64-bit dll, on a relatively large function).
Tried with both the macOS and Windows releases.

**Comment by mumbel** [comment]
@caheckman   came across this on 8668778fbb1af0891fda15fffa5a51e1a67c45f2.     PPC 32 BE

At this point it looks like symbol should not be NULL where class is global in HighVariable::saveXml.  I threw a LowLevelError with  `vn->printInfo()` in that case.

This pointed to a 2-byte undefined memory in .bss w/o any references (its +2 of word aligned address and there is a lwz to +0, lbz to +0 and lbz to +1 in the function).

By making this a 2-byte type or the +0 address a 4-byte type the decompiler is happy. 

The instruction given by printInfo makes zero sense as its a lwz reading from the argument (allocated on heap)
