### ISSUE TITLE
NPE using "Force field" in decompiler

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#4207]
```
java.lang.NullPointerException
	at ghidra.app.plugin.core.decompile.actions.ForceUnionAction.findStringIndex(ForceUnionAction.java:160)
	at ghidra.app.plugin.core.decompile.actions.ForceUnionAction.selectFieldNumber(ForceUnionAction.java:178)
	at ghidra.app.plugin.core.decompile.actions.ForceUnionAction.decompilerActionPerformed(ForceUnionAction.java:207)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.lambda$actionPerformed$1(AbstractDecompilerAction.java:76)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.performAction(DecompilerActionContext.java:116)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.actionPerformed(AbstractDecompilerAction.java:75)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

ghidra 10.2-dev 9c04807c8cbf3516ea4ff8c4321bc18d38f27661

**Comment by ryanmkurtz** [comment]
Not quite the same stack trace, but an NPE was fixed in a more recent commit for #4171.  Would you mind pulling master and trying again?

**Comment by jrmuizel** [comment]
Using the latest master (576c02c36925de50e82793243e58d70eb684f1e2) does not fix the problem. However, I confirmed that #4213 does fix it.
