### ISSUE TITLE
Decompiler interprets register value as pointer when math is done over a non-pointer type, even without any memory references created.

### ISSUE THREAD

**Issue by kitor** [NationalSecurityAgency/ghidra#5684]
**Describe the bug**
I have a following scenario:

There's a function which takes a 32 bit number as 1st argument. This value is just some arbitrary ID.
I created Enum type with size 4 which contain human readable names for those IDs - `PropID`

![image](https://github.com/NationalSecurityAgency/ghidra/assets/643531/dc0f2761-7ddb-4fae-8b6d-c09dea6081e5)

And the function in question is declared as is:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/643531/5dbad0e4-631c-4551-8443-74bd7134631d)

The behaviour I see is following:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/643531/3e79dd0e-3cb3-44ed-98ee-1c597bff69c8)

The first call is decompiled nice - displays value from `PropID` enum as argument. 2nd is also fine - PropID enum lacks entry for  `0x2040001` so it is displayed literally.

Third is not fine - `8000008d` *is* the literal PropID value, not `a pointer to undefined type, located at 0x8000008d` as Ghidra interprets it.

**What is different between first two, and the third one? (or where I think the bug is)**

First two load their values from memory constants. Eg, for the first one:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/643531/a03fd13a-c706-467f-af1e-a84bb5994603)

`PropID_source` contains literally the ID (in this case `0x80000030`) and type it set properly as `PropId`:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/643531/abef1e09-5596-4cef-9a71-6ec20710152d)

In the third ("broken") case code first loads `0x80000030` from `PropID_source`, then does some math (in this case adds `0x5D`).

![image](https://github.com/NationalSecurityAgency/ghidra/assets/643531/5172b834-792e-4e69-b39c-00ce13ab8f61)

And when any math happens, the issue happens. I see this pattern all over the code of this particular application (value is either added or subtracted - compiler optimization maybe? this saves 2 bytes per each computed value). 
**As you see, there are no memory references in that line (there was one from autoanalysis, but I removed it already).**

The behaviour doesn't change if I change argument type and source data type to `uint32_t`, decompiler still produces a cast from the pointer: `(uint32_t)&DAT_8000008d`
The issue is that Ghidra seems to treat computed value as a pointer, even though it was computed from non-pointer data type (Enum), and that all auto-generated memory references were removed.

So far I found no way to override this behaviour.

**Expected behavior**
The third line in decompiled code should read either
`Property::PropertyMgr::get_multicast_property(0x8000008d,&dwQuickreview,&bufSize);`
or 
`Property::PropertyMgr::get_multicast_property(WHATEVER_IS_SET_AT_0x8000008d_IN_ENUM,&dwQuickreview,&bufSize);`

`(PropId)&DAT_8000008d` is wrong.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.6
 - Ghidra Version: 10.3
 - Ghidra Origin: Official Github

**Comment by kitor** [comment]
I crafted some test binary, but I can't reproduce the issue exactly.

What I found so far is that if "computed" enum value happens to be also a valid memory map address, during auto analysis a memory reference is created there. This triggers decomp to display "incorrect" value.

However in my test binary when I delete reference on just "adds" instruction - this fixes the decomp. In the real one (where screenshots are from) I deleted all memory references and decomp still displays it improperly.

I see this even if I clear bytes from the "caller" function, remove it and re-create.

**Comment by caheckman** [comment]
I can't seem to reproduce this. Can you upload the output from the  "Debug Function Decompilation" on the function that incorrectly displays the enum value.  Its an action under the menu at the top right corner of the decompiler window.

**Comment by Wall-AF** [comment]
Is there a common thread here with #5347?

**Comment by kitor** [comment]
@caheckman Attached: [debug.zip](https://github.com/NationalSecurityAgency/ghidra/files/13063038/debug.zip)

**Comment by caheckman** [comment]
Thank you.  I reproduce this in Ghidra 10.3.  The problem should be addressed by  commit 514564292f7213910e41752e4d5961851ed90c14, which I believe is part of Ghidra 10.3.3 (and later).

**Comment by kitor** [comment]
I was sceptical but indeed after upgrade to 10.4 decompiler displays it properly. Thank you!

**Comment by kitor** [comment]
After some digging I see it partially fixed it. To be exact, issue, as reported - is fixed. However if statements still do this weird cast-thing:

```
      if ((undefined *)prop_id != &DAT_02000006) {
        iVar1 = iVar2;
        if ((undefined *)prop_id != &DAT_02070004) {
          if ((undefined *)prop_id == &DAT_02070007) {
```

(in this example, both `prop_id` and all memory sources of `02000006` `02070004` and `02070007` are set properly to PropID type).
Not sure if we should continue here, or open a new bug for that?
