### ISSUE TITLE
TOC/OPD/GOT/etc. is not processed in ELFs using PPC64 with 32-bit addressing

### ISSUE THREAD

**Issue by Bo98** [NationalSecurityAgency/ghidra#570]
**Describe the bug**
Take any ELF64 file using PowerPC64 and 32-bit addressing. I was using "PowerISA-Altivec-64-32addr", but any PPC64 language with 32-bit addressing will suffice.

This is handled by `PowerPC64_ElfExtension". It satisfies this check:

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Processors/PowerPC/src/main/java/ghidra/app/util/bin/format/elf/extend/PowerPC64_ElfExtension.java#L55

However when `processElf` is called then this check is included:

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Processors/PowerPC/src/main/java/ghidra/app/util/bin/format/elf/extend/PowerPC64_ElfExtension.java#L63

Which fails since it is equal to 32.

This may just be an unimplemented feature (I would need to see what assumptions the class makes), but we can clearly see that files imported using this PPC variation are not properly processed.

**To Reproduce**
1. Take any ELF file satisfying the aforementioned description. I used a PS3 EBOOT file.
2. Analyse this file.
3. Note how the `TOC_BASE` symbol is never created and how `r2` is not set at all in any function.

**Environment (please complete the following information):**
 - OS: Windows 10 Education 1809
 - Java Version: 12
 - Ghidra Version: 9.0.2

**Comment by Thalhammer** [comment]
If you set the r2 register to the correct TOC value, it sometimes works but in many cases fails to resolve the correct addresses in the decompiler, while it works fine in the disassembly window.

It generates code like this:
```c
puVar10 = &DAT_006b6f88;
....
iVar15 = **(puVar10 + -0x4888);
if(iVar15 != 0) {
...
```

The way it tries to access the location varies, sometimes it uses code like above, sometimes it tries to index it as an array and so on.

In the disassembly, it calculates the address just fine and also shows the label of that location.

**Comment by aerosoul94** [comment]
PS3 (PPU) ABI changes for reference:
> This appendix identifies the primary differences between the PPU ABI for Cell OS Lv-2 and the 64-bit
PowerPC ELF ABI.
• The size and alignment of a pointer are each 4 bytes. The PowerPC ABI defines these as 8 bytes.
• The size and alignment of long are each 4 bytes. The PowerPC ABI defines these as 8 bytes.
• The “plain” char type is signed char whereas the plain char type is an unsigned char in the
PowerPC ABI.
• Additional data types have been defined to represent some fundamental data types for OS and
library interfaces. (See Table 2.)
• Each function descriptor has two 32-bit address fields and no environment pointer. As a result, this
ABI does not support nested functions. Nested functions are a GCC language extension. For the
PowerPC ABI, each function descriptor consists of three 64-bit address fields: the address of the
function body, a pointer to the TOC referred to by the function, and the environment pointer used by
the function.
• The initial values of some registers have been changed, for process initialization.
• New relocation types, R_PPC64_TOC32, R_PPC64_DTPMOD32, R_PPC64_TPREL32 and
R_PPC64_DPTPREL32 are defined.
• The OS and ABI identifier in the ELF file header is defined as 102 for Cell OS Lv-2.
• VRSAVE is not required to be updated at runtime; however, it should be initialized to 0xffff_ffff.
• Traceback tables are not supported.
• The “extended precision” format is not supported.

Relocations are handled differently as well (note the use of patchseg and symseg): https://github.com/aerosoul94/ida_gel/blob/master/src/ps3/cell_loader.cpp#L334

OPD section recovery is likely necessary because they strip sections for retail binaries.

@Bo98 A workaround would be taking the TOC from the function descriptor, then setting the r2 register value for that function.

**Comment by ghidra1** [comment]
If using gcc to build, could you please provide a sample gcc execution command with options so we can try to reproduce a sample.  Are you working with an object file or fully linked binary?

**Comment by VelocityRa** [comment]
@ghidra1 Yeah you probably need a non-standard toolchain.
You can use this https://github.com/ps3dev/PSL1GHT, a homebrew PS3 SDK.

Else, I or someone else can provide _executable_ samples (instead of source code), if that's enough.

**Comment by VelocityRa** [comment]
Update:
@aerosoul94 discovered that if `r2` is added to the `<unaffected>` list here:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/PowerPC/data/languages/ppc_64_32.cspec#L96
then the decompiler issue with it is fixed.
Here's a comparison:
![image](https://user-images.githubusercontent.com/6632271/94754992-9df7a980-039b-11eb-976b-6d90e700e459.png)

Left is before the fix, right is after. Look specifically at the TOC-relative string references that are resolved after the fix.
(right is also on 9.2, but it doesn't matter, 9.1.2 is fixed with this too)

Let me know if you need anything else.

**Comment by VelocityRa** [comment]
Update: Even with the above fix and Ghidra 9.2 (build 1937), this still sometimes happens:

![image](https://user-images.githubusercontent.com/6632271/96327278-db696180-1040-11eb-912c-789141b160f0.png)

**Comment by Mc-muffin** [comment]
In the case of PS3 binaries this can still happen when the binary has more than one TOC pointer or the function has an indirect call (like a C++ virtual call). 
For the case when there's more than one TOC a thunk function is made for calls that cross this TOC boundary, the typical "r2 fixup" thunk I've seen so far looks like this:
```
std    r2,0x28(r1)  ; save r2
addis  r2,r2,0x####
addi   r2,r2,0x####
b      function_########
```
And the typical call site looks like this:
```
bl     thunk_function_#######
ld     r2,0x28(r1)   ; restore r2
```
As you can see the thunk saves `r2` and it's restored at the return place (when there's a single TOC in the binary the `ld r2,0x28(r1)` instruction is just a `nop`), it's this restoring what makes Ghidra think that `r2` is possibly spoiled so it uses that `var = &TOC_BASE;` construct.

For the case of indirect calls it's technically the same problem, `r2` is being load and restored but this time it's "inline", like:
```
lwz    r10,0x14(r9) ; get vtable function opd offset
lwz    r0,0x0(r10)  ; get function address
std    r2,0x28(r1)  ; save r2
mtspr  CTR,r0
lwz    r2,0x4(r10)  ; set function TOC
bctrl
ld     r2,0x28(r1)  ; restore r2
```
Note that this time `r2` is set 2 times, once for the virtual call (`lwz    r2,0x4(r10)` in the example) and the other is the regular restore like on thunk functions (`ld     r2,0x28(r1)`)

So the solution would be to make Ghidra somehow ignore this restoring of `r2` after these kind of calls, so far I've had success with just replacing the main offending instruction (`ld r2,0x28(r1)`) with a `nop` (`ori r0,r0,0x0`) across the binary but the indirect calls are a bit more complicated to do automatically as the register used to load the value from can be different, there's likely a more proper solution for this but I don't know enough about Ghidra to go about implementing that.

**Comment by dfanz0r** [comment]
So working with a few people we came up with an updated fix that resolves several issues with the current workarounds.
 
First we need to modify `ppc_64_32.cspec`to add the r2 register change as noted below:

```xml
        <register name="r31"/>
        <register name="r1"/>
        <register name="cr4"/>
        <!-- Start Change-->
        <!-- In cases where r2 does change, we assume it will get restored -->
        <register name="r2"/>
        <register name="r2Save"/>
      </unaffected>
      <pcode inject="uponreturn">
      	<body>
      		# Inject pcode when returning from a function call to place the r2Save
      		# value into 0x28(r1) which should be restored by the "ld r2,0x28(r1)" 
      		# which immediately follows calls which comply with the PPC64 ABI spec.
      		local saveR2ptr = r1 + 0x28;
      		*:8 saveR2ptr = r2Save; 
      	</body>
      </pcode>
      <!-- End Change-->
    </prototype>
  </default_proto>
```

File Path: `Ghidra\Processors\PowerPC\data\languages\ppc_64_32.cspec`

The next modification is to fix Ghidra not correctly marking thunks during analysis resulting in function calls wrapped in “bonus” function calls in the output. This will make the function call sites show the correct function name automatically.
Open the following file and add the block of code just before the`</patternlist>` tag :
`Ghidra\Processors\PowerPC\data\patterns\PPC_BE_patterns.xml`

```xml
  <pattern> 
    <data>
      11111000 01000001 00000000 00101000 # std r2,0x##(r1)
      00111100 01000010 ........ ........ # addis r2,r2,0x####
      00111000 01000010 ........ ........ # addi r2,r2,0x####
      010010.. ........ ........ ......00 # b 0x########
      </data>
    <codeboundary />
    <possiblefuncstart validcode="function" thunk="true" /> <!-- must be a function here -->
  </pattern>
```

This still doesn't fix most of the issues though. Ghidra doesn't know how to properly load the OPD from ps3 executables, and then by extension properly propagate the r2 TOC values through the executable. And so if you are working with a program that contains multiple TOC offsets it can be a huge pain.  I've been trying to work on a new script to go through and do simple block analysis to track control flow and manually propagate it as a script but it ofc a huge pain to implement.

A correct fix for the core analysis in ghidra would be ideal if this is still planned. Because essentially anytime r2 is modified through a load of any kind there is still a chance that the decompiler output is irrevocably messed up from that point onward.

**Comment by dfanz0r** [comment]
If @ghidra1 still wants to take a look into this here is a ps3 elf file which has the problematic behavior though since this is a ps3 executable you *may* need some of the scripts from https://github.com/clienthax/Ps3GhidraScripts to properly analyze it. 

[mage_g.zip](https://github.com/user-attachments/files/21049115/mage_g.zip)

Additionally one of the problems of trying to reproduce this with an isolated example to be built with the toolchain is that the codebase is required to be large enough to trigger TOC splitting by the compiler and that will be a bit difficult to do with a toy example.

**Comment by ghidra1** [comment]
> [@ghidra1](https://github.com/ghidra1) Yeah you probably need a non-standard toolchain. You can use this https://github.com/ps3dev/PSL1GHT, a homebrew PS3 SDK.
> 
> Else, I or someone else can provide _executable_ samples (instead of source code), if that's enough.

@VelocityRa That would be very helpful.  I think I need to allow the PowerPC64 ELF handler to accept them with a few tweaks but I hesitate to change without some sample to test against.  I am not in a position to extract or produce my own (e.g., EBOOT.ELF).

**Comment by ghidra1** [comment]
> If [@ghidra1](https://github.com/ghidra1) still wants to take a look into this here is a ps3 elf file which has the problematic behavior though since this is a ps3 executable you _may_ need some of the scripts from https://github.com/clienthax/Ps3GhidraScripts to properly analyze it.
> 
> [mage_g.zip](https://github.com/user-attachments/files/21049115/mage_g.zip)
> 
> Additionally one of the problems of trying to reproduce this with an isolated example to be built with the toolchain is that the codebase is required to be large enough to trigger TOC splitting by the compiler and that will be a bit difficult to do with a toy example.

@dfanz0r This file does not appear to contain any dynamic ELF relocations.

**Comment by VelocityRa** [comment]
@ghidra1 I probably shouldn't post a commercial game's EBOOT.BIN here, but you can likely repro the issue with RPCS3's test elfs like: https://github.com/RPCS3/rpcs3/blob/master/bin/test/pad_test.elf

If you want to test on an actual game, set up RPCS3 (firmware + a game) and then you can use `Utilities` -> `Decrypt PS3 Binary` to decrypt any `EBOOT.BIN`.

**Comment by ghidra1** [comment]
> If [@ghidra1](https://github.com/ghidra1) still wants to take a look into this here is a ps3 elf file which has the problematic behavior though since this is a ps3 executable you _may_ need some of the scripts from https://github.com/clienthax/Ps3GhidraScripts to properly analyze it.
> 
> [mage_g.zip](https://github.com/user-attachments/files/21049115/mage_g.zip)
> 
> Additionally one of the problems of trying to reproduce this with an isolated example to be built with the toolchain is that the codebase is required to be large enough to trigger TOC splitting by the compiler and that will be a bit difficult to do with a toy example.

I have modified (not yet pushed) the ELF Extension for ppc64 to better handle cases where 32-bit addressing (e.g., ID `PowerPC:BE:64:64-32addr`).  However, your `mage` sample lacks section names and symbols which `PowerPC64_ElfExtension` relies on.  There are quite a few ABI's and automatically identifying which one applies has proven to be very difficult.  I will take a look at the referenced scripts to see how it navigates the binary, although I suspect it relies on the user to run it when they know it is applicable.

**Comment by ghidra1** [comment]
I was able to get further with this by following the entry address into the .opd when section names have been stripped.

**Comment by VelocityRa** [comment]
@ghidra1 Thanks! IIRC the important file in PS3GhidraScripts is only `AnalyzePs3Binary.java`.
Btw, is there an email or something to privately reach you at to send more examples? Or a WIP build so that we can test your code perhaps. The used toolchain/ABI might might be slightly different for different games.
There's also a repository of all known PS3 game elfs with debugging symbols if that would be useful to figure out how the binaries are structured.

**Comment by dfanz0r** [comment]
> > If [@ghidra1](https://github.com/ghidra1) still wants to take a look into this here is a ps3 elf file which has the problematic behavior though since this is a ps3 executable you _may_ need some of the scripts from https://github.com/clienthax/Ps3GhidraScripts to properly analyze it.
> > [mage_g.zip](https://github.com/user-attachments/files/21049115/mage_g.zip)
> > Additionally one of the problems of trying to reproduce this with an isolated example to be built with the toolchain is that the codebase is required to be large enough to trigger TOC splitting by the compiler and that will be a bit difficult to do with a toy example.
> 
> I have modified (not yet pushed) the ELF Extension for ppc64 to better handle cases where 32-bit addressing (e.g., ID `PowerPC:BE:64:64-32addr`). However, your `mage` sample lacks section names and symbols which `PowerPC64_ElfExtension` relies on. There are quite a few ABI's and automatically identifying which one applies has proven to be very difficult. I will take a look at the referenced scripts to see how it navigates the binary, although I suspect it relies on the user to run it when they know it is applicable.

I have a debug build of the same application but it is too large to send over an attachment here which is why i sent the release version originally. So as @VelocityRa said what would be the best way to send that. (most of the file size is because of a ton of dwarf data)

**Comment by dfanz0r** [comment]
Something else worth noting it would likely be ideal if we can get a more proper cpu target that better matches the CellBE's powerpc 2.02 + Altvec extensions instead of the PowerISA 3.0 based target most people have been using for cell stuff afaik. Since there are some instructions that do not decode properly with the existing config.

**Comment by ghidra1** [comment]
This would be a perfect idea as a end-user Pull Request contribution since it may be more likely to happen in a timely fashion.
