### ISSUE TITLE
DWARF function parameter location evaluation regression

### ISSUE THREAD

**Issue by a1batross** [NationalSecurityAgency/ghidra#5982]
**Describe the bug**
After auto-analyze of a `gameui.so` binary in 10.4, I found that to get better decompile result I had to manually edit stack and shift everything by four bytes forward. For example, what was supposed to be `this` pointer is a second argument now. Where was first argument to a function is a garbage now.

The binary has DWARF2 debug information, so I clearly see that Ghidra addresses variables 4 bytes forward, where should've been `szString` is `szString + 4` now.

I checked older releases and regression did happen before 10.3 release. I also found older Ghidra I built from source code on my PC. It's on commit a27250f459266a658e36c26ec611a4bd8da918eb and issue doesn't reproduce here.

So clearly, it happened somewhere in between these two revisions.

**To Reproduce**
1. Load `gameui.so` from https://share.mentality.rip/pub/gameui.so. 
2. Run auto-analyze with default settings.
3. Go to _ZN8CTaskbar19ApplySchemeSettingsEPN5vgui27ISchemeE function
4. Wait until auto-analyze finishes and scroll down the first few decompiled lines:
```c++
  vgui2::Panel::ApplySchemeSettings((Panel *)0xa0d2a,pScheme);
  (**(code **)(*(int *)pScheme + 0xf4))(pScheme,0);
  piVar6 = (int *)vgui2::surface();
  (**(code **)(*piVar6 + 0x84))(piVar6,&tall,&imgW);
  piVar6 = (int *)vgui2::scheme();
  pcVar3 = *(code **)(*piVar6 + 0x28);
  pcVar7 = (char *)(**(code **)(*in_stack_00000008 + 8))();
  lVar8 = strtol(pcVar7,(char **)0x0,10);
  iVar9 = (*pcVar3)(piVar6,lVar8);
  *(int *)(pScheme + 0x160) = iVar9;
  if (tall < 0x401) {
    *(int *)(pScheme + 0x160) = (int)((float)iVar9 * 0.7);
  }
```

**Expected decompilation result**
This was taken from a27250f459266a658e36c26ec611a4bd8da918eb
```c++
  bVar25 = 0;
  vgui2::Panel::ApplySchemeSettings((Panel *)this,pScheme);
  (*(this->super_EditablePanel).super_Panel.super_IClientPanel._vptr.IClientPanel[0x3d])(this,0);
  piVar10 = (int *)vgui2::surface();
  (**(code **)(*piVar10 + 0x84))(piVar10,&tall,&imgW);
  piVar10 = (int *)vgui2::scheme();
  pcVar3 = *(code **)(*piVar10 + 0x28);
  pcVar11 = (char *)(**(code **)(*(int *)pScheme + 8))(pScheme,"InGameDesktop/GameMenuInset");
  lVar12 = strtol(pcVar11,(char **)0x0,10);
  iVar13 = (*pcVar3)(piVar10,lVar12);
  this->m_iGameMenuInset = iVar13;
  if (tall < 0x401) {
    this->m_iGameMenuInset = (int)((float)iVar13 * 0.7);
```

As you can see, it applied correct types and vtable, and first argument in `vgui2::Panel::ApplySchemeSettings` is correct `this` instead of garbage `0xa0d2a`.

**Environment (please complete the following information):**
 - OS: Ubuntu 23.04
 - Java Version: openjdk 17.0.9-ea 2023-10-17
 - Ghidra Version: 10.3
 - Ghidra Origin: official GitHub distro

**Comment by a1batross** [comment]
I bisected it, and it showed that 87c16f9cd0439427b6c3196c9af2470770c4ef6d is the first bad commit.

**Comment by dev747368** [comment]
If you can build your own ghidra locally, I can give you a small change that should fix this issue for you.

In DIEAggregate.java, line 742, change it from:
```java
			boolean isBadOffset = (beginning > cuBase);
```
to
```java
			boolean isBadOffset = (beginning > cuBase) && false;
```

This will disable hacky logic that was trying to catch bad values written by some toolchain we ran into in the past.

Additionally, just turning off the custom storage check box when editing the function will probably get your params back to where they need to be.

There are multiple issues with DWARF function parameters that need to be addressed and I've added this issue to our internal tracker as one of the failure-cases.

**Comment by a1batross** [comment]
I will try that.

Also, I found out that on older version the offset is still present despite a bit more correct output.

**Comment by dev747368** [comment]
Ok.  Eases my mind a little because I couldn't find an exact cause for the change between the old version and the current version.  Both have the same bad hack, just slightly different flow of logic when evaluating parameters.

**Comment by a1batross** [comment]
I checked it, it still happens on latest stable Ghidra version.

Meanwhile, the `isBadOffset` variable is gone. It seems this code has been refactored but this bug hasn't been fixed.

**Comment by dev747368** [comment]
@a1batross re: you most recent comment, I think you ran into a different issue in the dwarf loclist reading code after it was refactored to handle DWARF5, which hopefully should be fixed now.  :crossed_fingers: 

If not, please reopen this or a new issue.

**Comment by a1batross** [comment]
@dev747368 thank you very much! I will try to test it, for now I'm just resorting to 10.1.5 release and don't have enough time to test newer ones.
