### ISSUE TITLE
scripts not working

### ISSUE THREAD

**Issue by dot166** [NationalSecurityAgency/ghidra#6455]
**Describe the bug**
A clear and concise description of the bug.

the script is not executing see log and additional info.

**To Reproduce**
1. run a script using command in additional info

**Expected behavior**
it would execute

**Screenshots**
N/A

**Attachments**
```
INFO  REPORT: Analysis succeeded for file: file:///home/dot_______166/tm.exe (HeadlessAnalyzer)                        
ERROR Failed to find script in any script directory: /home/dot_______166/ghidra-headless-decompile/fix.java (GhidraScriptUtil)                                                                                                                  
ERROR REPORT SCRIPT ERROR: fix.java : The class could not be found. It must be the public class of the .java file: Failed to find source bundle containing script: /home/dot_______166/ghidra-headless-decompile/fix.java (HeadlessAnalyzer)
ghidra.app.script.GhidraScriptLoadException: The class could not be found. It must be the public class of the .java file: Failed to find source bundle containing script: /home/dot_______166/ghidra-headless-decompile/fix.java
at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:105)
at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:908)
at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1070)
at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1552)
at ghidra.app.util.headless.HeadlessAnalyzer.processWithLoader(HeadlessAnalyzer.java:1734)
at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1675)
at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1759)
at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:460)
at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
at ghidra.GhidraLauncher.launch(GhidraLauncher.java:78)
at ghidra.Ghidra.main(Ghidra.java:54)
Caused by: java.lang.ClassNotFoundException: Failed to find source bundle containing script: /home/dot_______166/ghidra-headless-decompile/fix.java                                                                                                     
at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:146)
at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:91)                                   ... 10 more                         
```
**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
 - Java Version: 17
 - Ghidra Version: latest
 - Ghidra Origin: official GitHub distro

**Additional context**

code:
```java
//Decompile an entire program

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

import ghidra.app.plugin.core.script.Ingredient;
import ghidra.app.plugin.core.script.IngredientDescription;
import ghidra.app.script.GatherParamPanel;
import ghidra.app.script.GhidraScript;
import ghidra.app.util.Option;
import ghidra.app.util.exporter.CppExporter;

public class fix extends GhidraScript implements Ingredient {

	@Override
	public void run() throws Exception {
		IngredientDescription[] ingredients = getIngredientDescriptions();
		for (IngredientDescription ingredient : ingredients) {
			state.addParameter(ingredient.getID(), ingredient.getLabel(), ingredient.getType(),
				ingredient.getDefaultValue());
		}
		// if (!state.displayParameterGatherer("Script Options")) {
		// 	return;
		// }

		String[] args = getScriptArgs();


		System.out.println("ARGS: " + Arrays.toString(args));

		// File outputFile = (File) state.getEnvironmentVar("COutputFile");
		File outputFile = new File(args[0]);


		CppExporter cppExporter = new CppExporter();
		List<Option> options = new ArrayList<Option>();
		options.add(new Option(CppExporter.CREATE_HEADER_FILE, new Boolean(false)));
		cppExporter.setOptions(options);
		cppExporter.setExporterServiceProvider(state.getTool());
		cppExporter.export(outputFile, currentProgram, null, monitor);
	}

	@Override
	public IngredientDescription[] getIngredientDescriptions() {
		IngredientDescription[] retVal = new IngredientDescription[] {
			new IngredientDescription("COutputFile", "Output C File", GatherParamPanel.FILE, "") };
		return retVal;
	}

}
```

command executed:
```bash
time /home/dot_______166/ghidra/support/analyzeHeadless . tmp_ghidra_project -import tm.exe  -scriptPath /home/dot_______166/ghidra-headless-decompile/ -postscript fix.java tm.cpp 
```

**Comment by ryanmkurtz** [comment]
Are you sure you are using JDK 17?  A similar looking error recently popped up when JDK 22 was being used.

**Comment by dot166** [comment]
when i run java -version i get the following output:
dot_______166@JAKE-PC:~/ghidra-headless-decompile$ java -version                                                        openjdk version "17.0.10" 2024-01-16                                                                                    OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)                                                           OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

**Comment by ryanmkurtz** [comment]
Would you mind just confirming what version is displayed on your Ghidra splash screen when it starts?

**Comment by dot166** [comment]
11.0.3

**Comment by ryanmkurtz** [comment]
Hmmm, the latest version of Ghidra should not even be allowed to launch with JDK 11.

**Comment by dot166** [comment]
Oh my mistake i put the ghidra version in that comment. My splash screen says
ghidra 11.0.3
Java 17.0.10

**Comment by ryanmkurtz** [comment]
Ok thanks, i'll think more about it.

**Comment by astrelsky** [comment]
> Ok thanks, i'll think more about it.

https://github.com/NationalSecurityAgency/ghidra/discussions/6449#discussioncomment-9178409


I see this problem roughly 80% of the time I try to run a java script. I think the easiest way to reproduce it is to delete the osgi folder, launch the code browser, close it while it is taking forever to setup the osgi stuff, let it error and then it should happen the next time you try to run a java script.

**Comment by ProgSys** [comment]
**Describe the bug**
I have the exactly same problem. Not even a simple hello world runs.

**To Reproduce**
Select any script in Script Manager like "HelloWorldScript.java" and try to run it.

**Expected behavior**
it would execute

**Screenshots**
N/A

**Environment (please complete the following information):**
    OS: Windows 10 x86_64
    Java Version: 17.0.10 or 22.0.1 (zip and set path variable)
    Ghidra Version: latest 
    Ghidra Origin: official GitHub distro

**Additional context:**
```
> Unable to load script: HelloWorldScript.java
>   detail: The class could not be found. It must be the public class of the .java file: HelloWorldScript
```

**Comment by cyrozap** [comment]
I'm having the same issue--custom scripts written in Java fail to run, but scripts included with Ghidra run without any problems.

It doesn't matter what version of Java I use--the result is the same whether I use Java 17, 21, or 22.

I'm running Ghidra on Arch Linux, and I'm using the latest version of Ghidra from the Arch repositories (11.0.3).

Here's a minimal reproducer script (`TestScript.java`):

```java
// Test script

import ghidra.app.script.GhidraScript;

public class TestScript extends GhidraScript {
	@Override
	public void run() {
	}
}
```

Placing that script in a custom script directory `$USER_HOME/Documents/Ghidra/scripts` results in the following console output:

```
> Unable to load script: TestScript.java
>   detail: The class could not be found. It must be the public class of the .java file: TestScript
```

The problem can be worked around by moving the script into `/opt/ghidra/Ghidra/Features/Base/ghidra_scripts/`. When I do that, `TestScript.java` executes successfully:

```
TestScript.java> Running...
TestScript.java> Finished!
```

**Comment by cyrozap** [comment]
In the process of trying to figure out what the problem was, I accidentally fixed it for myself. Here's approximately what I did--not sure what part of this fixed the issue:

1. Have Ghidra already open with a CodeBrowser window open.
2. `$ mkdir ~/ghidra_scripts` (it didn't exist before since I prefer to keep my scripts in other directories)
3. `$ mv TestScript.java ~/ghidra_scripts/`
4. "Display Script Manager" -> "Manage Script Directories" -> "Refesh state by cleaning and reactivating all enabled bundles"
5. Close Ghidra.
6. Open Ghidra.
7. Open CodeBrowser window.
8. "Display Script Manager" -> "Manage Script Directories" -> Enable `$USER_HOME/ghidra_scripts` (I might have refreshed again after this--I forget whether or not I did)
9. Run `TestScript.java `: **Results in successful script output in console.**
10. Run other custom scripts in other custom directories (not $USER_HOME/ghidra_scripts`): **Results in successful script output in console.**
11. `$ rm -r ~/ghidra_scripts`
12. "Display Script Manager" -> "Manage Script Directories" -> "Refesh state by cleaning and reactivating all enabled bundles"
13. Close Ghidra.
14. Open Ghidra.
15. Open CodeBrowser window.
16. Run other custom scripts in other custom directories (not $USER_HOME/ghidra_scripts`): **Results in successful script output in console.**
17. "Display Script Manager" -> "Manage Script Directories" -> "Refesh state by cleaning and reactivating all enabled bundles"
18. Run other custom scripts in other custom directories (not $USER_HOME/ghidra_scripts`): **Results in successful script output in console.**

So now custom scripts in custom directories works for me and I can't get it back into the broken state any more. If someone _really_ wants me to I can try restoring my `~/.ghidra` directory from yesterday's backup to see if things are broken again and maybe try to figure out the minimum number of steps required to fix the issue, but it would be kind of a pain for me to do all of that so I'd rather not unless it's deemed necessary for finding the root cause of the issue. Hopefully the information I've already posted will be enough for someone else to determine the root cause or find a simpler fix.

**Comment by astrelsky** [comment]
> In the process of trying to figure out what the problem was, I accidentally fixed it for myself. Here's approximately what I did--not sure what part of this fixed the issue:
> 
> 1. Have Ghidra already open with a CodeBrowser window open.
> 2. `$ mkdir ~/ghidra_scripts` (it didn't exist before since I prefer to keep my scripts in other directories)
> 3. `$ mv TestScript.java ~/ghidra_scripts/`
> 4. "Display Script Manager" -> "Manage Script Directories" -> "Refesh state by cleaning and reactivating all enabled bundles"
> 5. Close Ghidra.
> 6. Open Ghidra.
> 7. Open CodeBrowser window.
> 8. "Display Script Manager" -> "Manage Script Directories" -> Enable `$USER_HOME/ghidra_scripts` (I might have refreshed again after this--I forget whether or not I did)
> 9. Run `TestScript.java `: **Results in successful script output in console.**
> 10. Run other custom scripts in other custom directories (not $USER_HOME/ghidra_scripts`): **Results in successful script output in console.**
> 11. `$ rm -r ~/ghidra_scripts`
> 12. "Display Script Manager" -> "Manage Script Directories" -> "Refesh state by cleaning and reactivating all enabled bundles"
> 13. Close Ghidra.
> 14. Open Ghidra.
> 15. Open CodeBrowser window.
> 16. Run other custom scripts in other custom directories (not $USER_HOME/ghidra_scripts`): **Results in successful script output in console.**
> 17. "Display Script Manager" -> "Manage Script Directories" -> "Refesh state by cleaning and reactivating all enabled bundles"
> 18. Run other custom scripts in other custom directories (not $USER_HOME/ghidra_scripts`): **Results in successful script output in console.**
> 
> So now custom scripts in custom directories works for me and I can't get it back into the broken state any more. If someone _really_ wants me to I can try restoring my `~/.ghidra` directory from yesterday's backup to see if things are broken again and maybe try to figure out the minimum number of steps required to fix the issue, but it would be kind of a pain for me to do all of that so I'd rather not unless it's deemed necessary for finding the root cause of the issue. Hopefully the information I've already posted will be enough for someone else to determine the root cause or find a simpler fix.

https://github.com/NationalSecurityAgency/ghidra/discussions/6449#discussioncomment-9178409

**Comment by ZhouZiY** [comment]
save problem while using analyzeHeadless
`ERROR REPORT SCRIPT ERROR: print_program_name.java : The class could not be found. It must be the public class of the .java file: print_program_name not found by ab350b1b [2] (HeadlessAnalyzer) ghidra.app.script.GhidraScriptLoadException: The class could not be found. It must be the public class of the .java file: print_program_name not found by ab350b1b [2]`

**Comment by ryanmkurtz** [comment]
I could never reproduce this.  We can reopen it if people are still seeing a problem with Ghidra 11.3 or later.

**Comment by TerminalJockey** [comment]
currently seeing this problem on ghidra 11.3.2 win 11 jdk 21.0.3, tried fixes with deleting osgi folder, downgraded from adoptium jdk 21.0.6 to 21.0.3 with no luck as well

**Comment by jmcarter9t** [comment]
Had this happen yesterday this is after recently upgrading to 11.4:

- Could not use some of my scripts (same error messages as above -- cannot find...)
- I DO NOT have a ~/ghidra_scripts directory; I use a custom location.
- I nuked my ~/.config/ghidra/ghidra-version/osgi/compiled-bundles directory.
- I restarted ghidra and the compiled-bundles rebuilt.
- I checked for the presence of my scripts in the bundles - they were there.
- Same problem.
- I ADDED a ~/ghidra_scripts directory to my home and restarted and things started working fine.

<img width="506" height="659" alt="Image" src="https://github.com/user-attachments/assets/340a9b5a-6f5c-49d4-90c7-a335ee457956" />

Details of versions in screenshot

**Comment by ryanmkurtz** [comment]
I finally reproduced this.  I had to debug to reveal the real error:

```
Unable to resolve d8ec7da8 [1](R 1.0): missing requirement [d8ec7da8 [1](R 1.0)] osgi.ee; 
(osgi.ee=UNKNOWN) Unresolved requirements: [[d8ec7da8 [1](R 1.0)] osgi.ee; (osgi.ee=UNKNOWN)]
```

I've also see this report `java.awt` as an unresolved requirement.  I'm still investigating the true cause, but in 12.0/master you should start seeing the more detailed exception message appear.  It would be helpful if you could share that here.

**Comment by ryanmkurtz** [comment]
I fixed my above OSGi issue.  I will keep this issue open though in case there are similar issues in the upcoming 12.0 release.

**Comment by mrexodia** [comment]
Is there a known-good workaround for 11.4.2? I ran into this issue with a fresh macos 15.7.1, https://github.com/TorgoTorgo/Ghidra-App-Bundle

```
 ~/Downloads/jdk-25.jdk/Contents/Home/bin/java -version
openjdk version "25" 2025-09-16
OpenJDK Runtime Environment (build 25+36-3489)
OpenJDK 64-Bit Server VM (build 25+36-3489, mixed mode, sharing)
```

Nevermind, I fixed it by switching to https://www.oracle.com/java/technologies/javase/jdk21-archive-downloads.html and pressing refresh on the script directory list.

**Comment by targodan** [comment]
I just ran into the same issue. No java scripts worked at all, no matter if they were custom or shipped with ghidra. It seems like there is an issue with Ghidra and JDK 25. As soon as I switched down to JDK 21 (and cleared the build cache) everything worked.

**Comment by ashduiasdauidsa** [comment]
@targodan hi sorry to bother you but i am also facing the same issue. could you tell me how to clear the build cache?

**Comment by ryanmkurtz** [comment]
> I just ran into the same issue. No java scripts worked at all, no matter if they were custom or shipped with ghidra. It seems like there is an issue with Ghidra and JDK 25. As soon as I switched down to JDK 21 (and cleared the build cache) everything worked.

This sounds like the exact issue i fixed in cc4a4e5ed2d8d01b12c5e45fad8245dc9457a941 for the upcoming Ghidra 12.0.

**Comment by utkonos** [comment]
I'm hitting this on a fresh install with macOS ARM 26.1 with JDK 25.0.1 LTS and Ghidra 11.4.2.

There is an error in the Bundle Manager: `activating bundle: RESOLVE_ERROR -`

And then in the scripting console there is this error for any script I try `foo` is place holder for each script.

```
> Unable to load script: <foo>.java
>   detail: The class could not be found. It must be the public class of the .java file: <foo>
```

I downgraded to the older Java LTS 21.0.9, and then in the Bundle Manager running "Refresh state by cleaning and reactivating all enabled bundles". I needed to refresh twice before all the entries including my custom scripts directory turned green. But after that everything is working as expected.

**Comment by utkonos** [comment]
After upgrade to 11.4.3, I tried jdk-25 again. The problem is still here.

<img width="1001" height="576" alt="Image" src="https://github.com/user-attachments/assets/a8b9cb3e-491c-47bb-94e1-0f5ea751f89b" />

Reverting to jdk-21

**Comment by ryanmkurtz** [comment]
This JDK 25 issue should be fixed in the upcoming 12.0 release.
