### ISSUE TITLE
buildNatives_osx64 build is broken

### ISSUE THREAD

**Issue by mh-** [NationalSecurityAgency/ghidra#710]
**Describe the bug**
`gradle buildNatives_osx64` fails with error message
```
> Task :CabExtract:osx64CabExtractMake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o system.o `test -f 'mspack/system.c' || echo './'`mspack/system.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o cabd.o `test -f 'mspack/cabd.c' || echo './'`mspack/cabd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o lzxd.o `test -f 'mspack/lzxd.c' || echo './'`mspack/lzxd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o mszipd.o `test -f 'mspack/mszipd.c' || echo './'`mspack/mszipd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o qtmd.o `test -f 'mspack/qtmd.c' || echo './'`mspack/qtmd.c
rm -f libmspack.a
ar cru libmspack.a system.o cabd.o lzxd.o mszipd.o qtmd.o 
/opt/local/bin/ranlib: object: libmspack.a(system.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [libmspack.a] Error 1
make: *** [all] Error 2

> Task :CabExtract:osx64CabExtractMake FAILED
```

**To Reproduce**
This applies to the current Ghidra github repo, the last commit was https://github.com/NationalSecurityAgency/ghidra/commit/cafbb77db0a2120c529aef45d2d6bc47fa1edc29
```
mkdir ~/git2
cd ~/git2
git clone https://github.com/NationalSecurityAgency/ghidra.git
cd ghidra/
gradle eclipse
gradle prepDev -x yajswDevUnpack eclipse
mkdir -p /git2/ghidra.bin/GhidraBuild/EclipsePlugins/GhidraDev/buildDependencies/
cp ~/git/ghidra.bin/GhidraBuild/EclipsePlugins/GhidraDev/buildDependencies/* ~/git2/ghidra.bin/GhidraBuild/EclipsePlugins/GhidraDev/buildDependencies/
gradle prepDev -x yajswDevUnpack eclipse

gradle buildNatives_osx64
```

**Expected behavior**
Build should work.

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: openjdk 11.0.2 2019-01-15
 - Ghidra Version: fresh clone from github

**Comment by ryanmkurtz** [comment]
Did it used to build for you or is this your first attempt?

**Comment by ryanmkurtz** [comment]
You may want to pull and try again.  The next commit is [Corrected CabExtract build issues](https://github.com/NationalSecurityAgency/ghidra/commit/8dfffdd5dbfcaf3b32ba759dc1b2355f6f3f8c00).

**Comment by mh-** [comment]
Yes, this is not my first build of the decompiler, it did build for me with a previous pull.

This is the output from git log:
```
$ git log
commit cafbb77db0a2120c529aef45d2d6bc47fa1edc29 (HEAD -> master, origin/master, origin/HEAD)
Merge: d428f30a b6c8c6be
Author: Ryan Kurtz <ryanmkurtz@users.noreply.github.com>
Date:   Mon Jun 17 10:54:28 2019 -0400

    Merge remote-tracking branch 'origin/GT-2926_dev747368_DmgClientFileSystem'

commit d428f30a85dd7866b1e78c9f72a7f47676e8004a
Merge: 14f06985 484a4bce
Author: Ryan Kurtz <ryanmkurtz@users.noreply.github.com>
Date:   Mon Jun 17 10:31:53 2019 -0400

    Merge remote-tracking branch 'origin/patch'
    
    Conflicts:
            Ghidra/Features/ByteViewer/src/main/java/ghidra/app/plugin/core/byteviewer/ByteViewerPlugin.java

commit 14f0698554df9124f17b5330ffaeb789400e1eff
Author: Ryan Kurtz <ryanmkurtz@users.noreply.github.com>
Date:   Mon Jun 17 09:36:21 2019 -0400

    GT-2937: Fixing PDB file move.

commit 4918660b002c93afd0f9f8fb3f75e6aeda482eda
Merge: 8843a709 56a53cb7
Author: Ryan Kurtz <ryanmkurtz@users.noreply.github.com>
Date:   Mon Jun 17 09:03:21 2019 -0400

    Merge remote-tracking branch 'origin/GT-2912_dev747368_cpio_filesystem_fix'

commit 484a4bce5656655186f62b391eb2b3360d2d0d17 (origin/patch)
Author: dragonmacher <48328597+dragonmacher@users.noreply.github.com>
Date:   Fri Jun 14 18:12:05 2019 -0400

    GT-2927 - review fixes

commit 12fffa922e55c84c229597d137bdac732455485f
Author: dragonmacher <48328597+dragonmacher@users.noreply.github.com>
Date:   Fri Jun 14 17:59:45 2019 -0400

    GT-2927 - Fixed Listing cursor not restoring correctly at startup

commit 8843a709474ea80c88499772ec9927bfe5b83098
Author: ghidra1 <ghidra1@users.noreply.github.com>
Date:   Fri Jun 14 15:50:10 2019 -0400

    Additional GPL build fixes

commit b6c8c6be2bbd984fcc6565242c9328b5b9a18af9
Author: dev747368 <48332326+dev747368@users.noreply.github.com>
Date:   Thu Jun 13 18:11:39 2019 -0400

    GT-2926 remove special case matching for zlib headers in DMG filesystem
    (#583).
    
    Some pre-mac appstore DMGs contained zlib compressed payloads.  The
    naive check for zlib enabled the DMG file system to catch those cases,
    at the expense of false positives for other zlib content.
    
    This commit stops the DMG file system from claiming zlib formatted
    files.
    
    Also fix unreleased filehandle in DmgDecryptorStream

commit 8dfffdd5dbfcaf3b32ba759dc1b2355f6f3f8c00
Author: ghidra1 <ghidra1@users.noreply.github.com>
Date:   Thu Jun 13 18:54:47 2019 -0400

    Corrected CabExtract build issues

commit 7e80e70465f0d77e80c04a2f7501b41fb1e7d89e
Author: ghidra1 <ghidra1@users.noreply.github.com>
Date:   Thu Jun 13 16:37:47 2019 -0400

    Restored build cleanup of assembly area
(...)
```

So the commit you mentioned is already included:
```
commit 8dfffdd5dbfcaf3b32ba759dc1b2355f6f3f8c00
Author: ghidra1 <ghidra1@users.noreply.github.com>
Date:   Thu Jun 13 18:54:47 2019 -0400

    Corrected CabExtract build issues
```
But the problem is still:
```
$ gradle buildNatives_osx64

> Task :CabExtract:configureCabExtract
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking whether time.h and sys/time.h may both be included... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for sys/types.h... yess]
checking for sys/stat.h... yes5s]
checking for stdlib.h... yes [5s]
checking for string.h... yes [5s]
checking for memory.h... yes [5s]
checking for strings.h... yes[5s]
checking for inttypes.h... yes6s]
checking for stdint.h... yes [6s]
checking for unistd.h... yes [6s]
checking ctype.h usability... yes
checking ctype.h presence... yes]
checking for ctype.h... yes
checking errno.h usability... yes
checking errno.h presence... yes]
checking for errno.h... yes
checking fnmatch.h usability... yes
checking fnmatch.h presence... yes
checking for fnmatch.h... yes
checking libintl.h usability... no
checking libintl.h presence... no
checking for libintl.h... no
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking wchar.h usability... yes
checking wchar.h presence... yes]
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for inttypes.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline[9s]
checking for mode_t... yesNG [9s]
checking for off_t... yesING [9s]
checking for size_t... yesNG [9s]
checking size of off_t... 8G [9s]
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for working POSIX fnmatch... yes
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for mkdir... yesING [10s]
checking for _mkdir... noING [10s]
checking whether mkdir takes one argument... no
checking for sys/time.h... (cached) yes
checking for unistd.h... (cached) yes
checking for alarm... yes
checking for working mktime... no]
checking for memcpy... yesNG [11s]
checking for memmove... yesG [11s]
checking for strcasecmp... yes11s]
checking for strchr... yesNG [11s]
checking for towlower... yes [11s]
checking for utime... yesING [11s]
checking for utimes... yesNG [11s]
checking for getopt_long... yes2s]
checking for working alloca.h... yes
checking for alloca... yesNG [12s]
checking for mbstate_t... yes[12s]
checking for working POSIX fnmatch... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating cabextract.spec
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

> Task :CabExtract:osx64CabExtractMake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o system.o `test -f 'mspack/system.c' || echo './'`mspack/system.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o cabd.o `test -f 'mspack/cabd.c' || echo './'`mspack/cabd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o lzxd.o `test -f 'mspack/lzxd.c' || echo './'`mspack/lzxd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o mszipd.o `test -f 'mspack/mszipd.c' || echo './'`mspack/mszipd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o qtmd.o `test -f 'mspack/qtmd.c' || echo './'`mspack/qtmd.c
rm -f libmspack.a
ar cru libmspack.a system.o cabd.o lzxd.o mszipd.o qtmd.o 
/opt/local/bin/ranlib: object: libmspack.a(system.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [libmspack.a] Error 1
make: *** [all] Error 2

> Task :CabExtract:osx64CabExtractMake FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CabExtract:osx64CabExtractMake'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16s
4 actionable tasks: 4 executed
```

**Comment by ryanmkurtz** [comment]
Ok, I'll have to check with someone else to see what has changed.  In the meantime, we just pushed new commits if you want to try with the absolute latest.

**Comment by mh-** [comment]
Ok, I wanted to try with the absolute latest and did:
```
git fetch
git pull
gradle clean
gradle eclipse
gradle prepDev -x yajswDevUnpack eclipse
gradle buildNatives_osx64
```
and the last command still fails:
```
> Task :CabExtract:osx64CabExtractMake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o system.o `test -f 'mspack/system.c' || echo './'`mspack/system.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o cabd.o `test -f 'mspack/cabd.c' || echo './'`mspack/cabd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o lzxd.o `test -f 'mspack/lzxd.c' || echo './'`mspack/lzxd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o mszipd.o `test -f 'mspack/mszipd.c' || echo './'`mspack/mszipd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o qtmd.o `test -f 'mspack/qtmd.c' || echo './'`mspack/qtmd.c
rm -f libmspack.a
ar cru libmspack.a system.o cabd.o lzxd.o mszipd.o qtmd.o 
/opt/local/bin/ranlib: object: libmspack.a(system.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [libmspack.a] Error 1
make: *** [all] Error 2

> Task :CabExtract:osx64CabExtractMake FAILED
```

Interestingly, when I run the buildNatives command a second time, the result is
```
> Task :CabExtract:osx64CabExtractMake FAILED
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o cabextract.o `test -f 'src/cabextract.c' || echo './'`src/cabextract.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o md5.o md5.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o mktime.o mktime.c
mktime.c:367:7: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  if (TIME_T_MAX / INT_MAX / 366 / 24 / 60 / 60 < 3)
      ^~~~~~~~~~
mktime.c:90:21: note: expanded from macro 'TIME_T_MAX'
# define TIME_T_MAX TYPE_MAXIMUM (time_t)
                    ^~~~~~~~~~~~~~~~~~~~~
mktime.c:77:41: note: expanded from macro 'TYPE_MAXIMUM'
#define TYPE_MAXIMUM(t) ((t) (~ (t) 0 - TYPE_MINIMUM (t)))
                                        ^~~~~~~~~~~~~~~~
mktime.c:76:20: note: expanded from macro 'TYPE_MINIMUM'
                              ? ~ (t) 0 << (sizeof (t) * CHAR_BIT - 1) : (t) 0))
                                ~~~~~~~ ^
1 warning generated.
gcc  -g -O2   -o cabextract cabextract.o md5.o libmspack.a  mktime.o 
ld: archive has no table of contents file 'libmspack.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cabextract] Error 1
make: *** [all] Error 2

FAILURE: Build failed with an exception.
```

and when I run it a third time, the result is:
```
> Task :CabExtract:osx64CabExtractMake FAILED
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc  -g -O2   -o cabextract cabextract.o md5.o libmspack.a  mktime.o 
ld: archive has no table of contents file 'libmspack.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cabextract] Error 1
make: *** [all] Error 2
```

and further attempts yield the same result.

**Comment by ryanmkurtz** [comment]
I just did a `clone`, setup the `~/.gradle/init.d/repos.gradle` file, got dependencies for `FileFormats` and `DMG`, then ran `gradle buildNatives_osx64` and it worked.  

I'm on macOS High Sierra.  Did you recently change anything about your OS or build tools on your system?

**Comment by mh-** [comment]
I use the most recent macOS Mojave 10.14.5
I didn't change anything recently, and I can still build an older version of Ghidra (06 Jun 2019). A commit after that must have broken the build for me.

**Comment by ryanmkurtz** [comment]
I'm running out of ideas.  In your repo where it's failing, what happens if you rollback to the same commit you know is working in your other repo?  If that works, you could do a binary search through the commits to figure out what exactly broke it for you.

**Comment by mh-** [comment]
`git reset --hard 3b999fd86eddbb55861869286d10f4fc6fddc078` breaks it 
(and subsequent commits do not fix it)

> commit 3b999fd86eddbb55861869286d10f4fc6fddc078 (HEAD -> master)
Author: ghidra1 <ghidra1@users.noreply.github.com>
Date:   Thu Jun 13 14:06:13 2019 -0400
    Corrected GPL build issues

`git reset --hard a524ae4d7c0d7095f14c5496840f492c6a091656` still works.

**Comment by ryanmkurtz** [comment]
Thanks for taking the time to track that down.  I see that a few commits later additional GPL fixes were put in to fix cabextract.  I'll have to check with @ghidra1 to see what that was about.  It sounds like he only fixed it partially.

**Comment by ryanmkurtz** [comment]
Could you try unpacking and building [cabextract-1.6.tar.gz](https://github.com/NationalSecurityAgency/ghidra/blob/master/GPL/CabExtract/data/cabextract-1.6.tar.gz) yourself to see if that succeeds?  It should just be a `./configure` and `make`.  If it succeeds, then we are doing something wrong with fixing up the timestamps that Gradles messes up.

On the older commit where the build was succeeding, we weren't even kicking off the build of cabextract...that's why it appeared to be working.

**Comment by mh-** [comment]
I tried this:
```
cd GPL/CabExtract/build/cabextract-1.6/
make clean
./configure
make
```
Result is the same:
```
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o system.o `test -f 'mspack/system.c' || echo './'`mspack/system.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o cabd.o `test -f 'mspack/cabd.c' || echo './'`mspack/cabd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o lzxd.o `test -f 'mspack/lzxd.c' || echo './'`mspack/lzxd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o mszipd.o `test -f 'mspack/mszipd.c' || echo './'`mspack/mszipd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o qtmd.o `test -f 'mspack/qtmd.c' || echo './'`mspack/qtmd.c
rm -f libmspack.a
ar cru libmspack.a system.o cabd.o lzxd.o mszipd.o qtmd.o 
/opt/local/bin/ranlib: object: libmspack.a(system.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [libmspack.a] Error 1
make: *** [all] Error 2
```
`$ /opt/local/bin/ranlib -V` prints `Apple Inc. version cctools-895`

**Comment by ryanmkurtz** [comment]
Can you unpack GPL/CabExtract/data/cabextract-1.6.tar.gz to somewhere outside of the Ghidra installation directory and try to build it?  We are concerned that the timestamps associated with the files unpacked by Gradle are causing the issue.  If you unpack the .tar.gz file yourself, it will eliminate Gradle as a possibility.

**Comment by mh-** [comment]
Yes, but same result:
```
(use Mac Finder to copy cabextract-1.6.tar.gz to ~/ and extract it there)

cd ~/cabextract-1.6
./configure
make
```

```
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o system.o `test -f 'mspack/system.c' || echo './'`mspack/system.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o cabd.o `test -f 'mspack/cabd.c' || echo './'`mspack/cabd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o lzxd.o `test -f 'mspack/lzxd.c' || echo './'`mspack/lzxd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o mszipd.o `test -f 'mspack/mszipd.c' || echo './'`mspack/mszipd.c
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o qtmd.o `test -f 'mspack/qtmd.c' || echo './'`mspack/qtmd.c
rm -f libmspack.a
ar cru libmspack.a system.o cabd.o lzxd.o mszipd.o qtmd.o 
/opt/local/bin/ranlib: object: libmspack.a(system.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[1]: *** [libmspack.a] Error 1
make: *** [all] Error 2
```

**Comment by ryanmkurtz** [comment]
That would point to there being something about your build tools not being able to build this package...nothing to do with Ghidra really.  I'll have to do some googling to see if other people are having problems building this on Mojave.  Could you try building the [latest version of cabextract](https://www.cabextract.org.uk/)?  Maybe they fixed something for your platform.

**Comment by mh-** [comment]
Hmmm, well, downloading and trying to make cabextract-1.9.1 yields the same error :(

**Comment by mh-** [comment]
Ok, I found the problem - apparently my `ranlib` ("Apple Inc. version cctools-895") was installed with another package, maybe libtools (?), and didn't match `ar`. 

Now, with
```
$ ranlib -V
Apple Inc. version cctools-927.0.2
```
everything builds ok.

It generates a warning
```
mktime.c:367:7: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  if (TIME_T_MAX / INT_MAX / 366 / 24 / 60 / 60 < 3)
      ^~~~~~~~~~
mktime.c:90:21: note: expanded from macro 'TIME_T_MAX'
# define TIME_T_MAX TYPE_MAXIMUM (time_t)
                    ^~~~~~~~~~~~~~~~~~~~~
mktime.c:77:41: note: expanded from macro 'TYPE_MAXIMUM'
#define TYPE_MAXIMUM(t) ((t) (~ (t) 0 - TYPE_MINIMUM (t)))
                                        ^~~~~~~~~~~~~~~~
mktime.c:76:20: note: expanded from macro 'TYPE_MINIMUM'
                              ? ~ (t) 0 << (sizeof (t) * CHAR_BIT - 1) : (t) 0))
                                ~~~~~~~ ^
1 warning generated.
```
but it builds :)

Thanks for your help.

**Comment by wanchouchou** [comment]
**Thanks for your information, it helps me a lot**.

I have also occurred this problem after I updated my MAC with command `brew upgrade`. 

But my error info is:
```
ld: warning: ignoring file libmspack.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_mspack_create_cab_decompressor", referenced from:
      _main in cabextract.o
  "_mspack_destroy_cab_decompressor", referenced from:
      _main in cabextract.o
  "_mspack_sys_selftest_internal", referenced from:
      _main in cabextract.o
ld: symbol(s) not found for architecture x86_64
```

Using command `nm libmspack.a | grep _mspack_create_cab_decompressor`, I get:

```
0000000000000000 T _mspack_create_cab_decompressor
```

It's clear that I have successfully built and archived the target functions, but why I cannot link them?

The command `ar -V` and `ranlib -V` gives me the result:
```
GNU ar/ranlib (GNU Binutils) 2.37
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```
So it's not about the incompatible between **AR** and **RANLIB**. What about the **LD**? Then I use system default **AR** and **RANLIB** instead:
```
Apple Inc. version cctools-959.0.1
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: no archives specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib [-sactfqLT] [-] archive [...]
```
Build again. Bingo! Compile successfully.

**CONCLUSION: The AR and RANLIB from GNU Binutils  does not compatible with the system linker LD on mac OSX, we should use the system default toolchains.**
