### ISSUE TITLE
Back-port floating-point support from the ARMv8 language to ARMv6

### ISSUE THREAD

**Issue by aboood40091** [NationalSecurityAgency/ghidra#7987]
The ARMv6 language is unable to decode perfectly valid FP instructions. Example:

![Image](https://github.com/user-attachments/assets/091187b5-ec52-4dae-831e-c7cd1288863a)

The ARMv8 language is able to decode these instructions correctly. Same example with the language set to ARMv8:

![Image](https://github.com/user-attachments/assets/0af3a2e6-a0ae-426c-bb97-0bfab22fc457)

For reference, these instructions also decode correctly using the ARMv7 language:

![Image](https://github.com/user-attachments/assets/82e1a487-bb6d-4fa1-ae96-f3527193b425)

However, the ARMv8 language is better implemented. For example, note the removal of the `VectorSignedToFloat` function call.

**Comment by f-raZ0R** [comment]
Are you using the latest version of ghidra? this was already fixed in 11.3

**Comment by aboood40091** [comment]
Do you mean 11.3.1? I am currently using 11.3. I'll give 11.3.1 a try.

**Comment by aboood40091** [comment]
Oh, I see that you've already reported this previously in this issue: #7259.
It's part of the 11.3 milestone, so I'm not sure why I still have the problem. I'll verify that I have the latest changes and not using some old DEV version.

**Comment by f-raZ0R** [comment]
if you disassemble and then reassemble the cdp instruction, does it fix itself?

**Comment by aboood40091** [comment]
No, I was indeed simply on a DEV version of 11.3 that didn't have that commit yet. My apologies. The `vmul.f32` instruction is being decoded correctly now.

However, the ARMv8 language still has better processing of `vcvt.f32.s32`, eliminating the `VectorSignedToFloat` call in the decompilation when using either ARMv6 or ARMv7, which is desirable and may justify keeping this issue open. If the issue needs to be renamed, please let me know.

**Comment by aboood40091** [comment]
NVM, even that was reported in #7890, which would still make this a duplicate issue. Welp. I should do better searching next time.

**Comment by f-raZ0R** [comment]
> No, I was indeed simply on a DEV version of 11.3 that didn't have that commit yet. My apologies. The `vmul.f32` instruction is being decoded correctly now.
> 
> However, the ARMv8 language still has better processing of `vcvt.f32.s32`, eliminating the `VectorSignedToFloat` call in the decompilation when using either ARMv6 or ARMv7, which is desirable and may justify keeping this issue open. If the issue needs to be renamed, please let me know.

make sure to recompile all vmul instructions regardless, since which register they target might be incorrect if upgrading from 11.2 to 11.3, not sure why
