### ISSUE TITLE
ARM `vcvt.f32.f64` not recognized

### ISSUE THREAD

**Issue by CreepNT** [NationalSecurityAgency/ghidra#8380]
**Describe the bug**
This applies at least to `ARM:LE:32:v7` (v1.107) **in Thumb mode**.

Instructions `vcvt.f32.f64` are not recognized properly, instead falling back to the default (and effectless) `cdp p11, ...` form.

**To Reproduce**
1. Import binary with `vcvt.f32.f64` instruction
2. Disassemble

**Expected behavior**
Instruction should be disassembled properly.

**Screenshots**

<img width="657" height="199" alt="Image" src="https://github.com/user-attachments/assets/462f1014-6081-4bc5-9c5c-5a1b556086d6" />

vs Capstone

<img width="304" height="114" alt="Image" src="https://github.com/user-attachments/assets/951933c5-8b74-4728-ad41-0b0ae3cd6521" />

(note how the sequence ends with a `vstr.32 s4, [r0]` so there is definitely something expected in `s4`)

Built-in assembler attempts to emit `b6 ee c2 2b` when asking for `vcvt.f32.f64 s4, d2`
<img width="518" height="188" alt="Image" src="https://github.com/user-attachments/assets/7f24040e-8757-4abe-b3c8-394857309214" />
However, Capstone disassembles this to `vrintz.f64 d2, d2` instead.

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 21.0.1
 - Ghidra Version: 11.4
 - Ghidra Origin: official GitHub distro 

**Additional context**
N/A

**Comment by f-raZ0R** [comment]
"Ghidra Version: 10.4"
Update Ghidra, this was already fixed in a later version.

**Comment by CreepNT** [comment]
> "Ghidra Version: 10.4" Update Ghidra, this was already fixed in a later version.

Whoops, typo - I meant 1**1**.4 aka latest (at time of writing).

Confirmed still broken on 11.4.1, same binary still doesn't disassemble properly and `Patch Instruction` is still wrong... unless I missed something?

<img width="637" height="259" alt="Image" src="https://github.com/user-attachments/assets/9238d1c9-2182-4a2a-ba99-a92bb0c96442" />

<img width="643" height="255" alt="Image" src="https://github.com/user-attachments/assets/fd5e97f1-99cf-4188-8024-0498ad78db70" />

**Comment by CreepNT** [comment]
Still broken in Ghidra 12.0 (I have modified a toy binary instead of checking the existing one, but it shouldn't matter too much)

<img width="492" height="153" alt="Image" src="https://github.com/user-attachments/assets/0de46b0f-441c-41d0-839b-04d8d051413c" />

<img width="574" height="191" alt="Image" src="https://github.com/user-attachments/assets/ffc2e832-1330-40ec-86c1-6ac237b5779d" />

**Comment by GhidorahRex** [comment]
I do have a fix in for this. I'm hoping to get it merged into master soon. The patch corrects a number off ARM v7 NEON disassembly errors.

**Comment by CreepNT** [comment]
Seems fixed in Ghidra 12.1.3 (and maybe earlier, I only just rechecked the binary) - thanks!

I just had to clear function bytes and re-disassemble to fix disassembly and decompilation:

<img width="1377" height="597" alt="Image" src="https://github.com/user-attachments/assets/f8c94c73-2f9a-4190-8f35-67eb018407f1" />

<details><summary>Details</summary>
<p>

Before clearing the function bytes, the instructions were appearing BACKWARDS: `vcvt.f64.f32 d2, s4` instead of `vcvt.f32.f64 s4, d2`. Decompilation was still also wrong:
<img width="1306" height="221" alt="Image" src="https://github.com/user-attachments/assets/3a222307-b23b-4587-9af1-088895f2e5d3" />

I'm assuming this is "expected" behavior.

</p>
</details> 

Closing the issue since it seems fixed.
