### ISSUE TITLE
Windows x86 PE Exception Handling creates overlapping functions

### ISSUE THREAD

**Issue by FeeeeK** [NationalSecurityAgency/ghidra#8459]
**Describe the bug**
The program import and `Windows x86 PE Exception Handling` doesn't ignore overlapping entries in the `IMAGE_RUNTIME_FUNCTION_ENTRY_ARRAY`

**To Reproduce**
1. Import program with unwind info
2. Go through the IMAGE_RUNTIME_FUNCTION_ENTRY_ARRAY, and you will find overlapping functions.

**Expected behavior**
No overlapping functions are created

**Screenshots**
<img width="633" height="836" alt="Image" src="https://github.com/user-attachments/assets/8ad82a24-8294-485e-bda3-2bcebce8fda6" />

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 21
 - Ghidra Version: 11.4.1
 - Ghidra Origin: github

**Comment by ryanmkurtz** [comment]
This should be fixed in `patch` and `master` branches, if you would like to test to make sure.  Thanks!

**Comment by axd1x8a** [comment]
> This should be fixed in `patch` and `master` branches, if you would like to test to make sure. Thanks!

@ryanmkurtz I tried the version from the `patch` branch, yet the issue persists, but it's less severe now

**Comment by axd1x8a** [comment]
<img width="1400" height="1202" alt="Image" src="https://github.com/user-attachments/assets/da89b9bb-45ce-40e8-ac20-dd89942b4301" />

<img width="1428" height="409" alt="Image" src="https://github.com/user-attachments/assets/a2f57488-b63a-4b52-b25a-06f63f920851" />

<img width="1433" height="1137" alt="Image" src="https://github.com/user-attachments/assets/3ef23f1d-f539-4e73-9bd1-88fed3433ec6" />

**Comment by axd1x8a** [comment]
Here's a script to clean this up in case someone needs it

```java
// Reads an array of _IMAGE_RUNTIME_FUNCTION_ENTRY structures and deletes
// any functions where the associated UNWIND_INFO has the CHAININFO flag set.
//@author Axd1x8a
//@category Analysis

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.data.Array;
import ghidra.program.model.data.DataType;
import ghidra.program.model.listing.Function;
import ghidra.program.model.mem.Memory;
import ghidra.program.model.mem.MemoryAccessException;

public class DeleteChainedUnwindInfoFunctions extends GhidraScript {

    private static final int RUNTIME_FUNCTION_ENTRY_SIZE = 12;
    private static final int UNW_FLAG_CHAININFO = 0x4;
    private static final int UNWIND_INFO_FLAGS_SHIFT = 3;
    private static final int UNWIND_INFO_FLAGS_MASK = 0x1F;

    private Address imageBase;

    @Override
    public void run() throws Exception {
        if (currentProgram == null) {
            printerr("There is no program open.");
            return;
        }
        if (currentLocation == null) {
            printerr(
                "Please place the cursor at the start of the _IMAGE_RUNTIME_FUNCTION_ENTRY array.");
            return;
        }

        imageBase = currentProgram.getImageBase();
        Address startOfEntries = currentLocation.getAddress();
        Memory memory = currentProgram.getMemory();

        DataType dataType = currentProgram.getListing().getDataAt(startOfEntries).getDataType();
        if (dataType == null || !(dataType instanceof Array)) {
            printerr(
                "Invalid data type for _IMAGE_RUNTIME_FUNCTION_ENTRY array. Please define an array of the correct size at the cursor.");
            return;
        }

        int entryCount = ((Array) dataType).getNumElements();
        println("Analyzing " + entryCount + " unwind entries for chained info...");
        println("--------------------------------------------------");

        monitor.initialize(entryCount);
        monitor.setMessage("Analyzing unwind entries...");

        int chainedCount = 0;

        for (int i = 0; i < entryCount; i++) {
            if (monitor.isCancelled()) {
                break;
            }
            monitor.setProgress(i);

            Address currentEntryAddress = startOfEntries.add(i * RUNTIME_FUNCTION_ENTRY_SIZE);
            int beginRva = memory.getInt(currentEntryAddress);
            int unwindInfoRva = memory.getInt(currentEntryAddress.add(8));

            if (beginRva == 0) {
                continue;
            }

            Address functionAddress = imageBase.add(beginRva);
            Address unwindInfoAddress = imageBase.add(unwindInfoRva);

            try {
                byte versionAndFlags = memory.getByte(unwindInfoAddress);
                byte flags =
                    (byte) ((versionAndFlags >> UNWIND_INFO_FLAGS_SHIFT) & UNWIND_INFO_FLAGS_MASK);

                if ((flags & UNW_FLAG_CHAININFO) == UNW_FLAG_CHAININFO) {
                    Function func = getFunctionAt(functionAddress);
                    if (func != null) {
                        chainedCount++;
                        println("Function " + func.getName() + " at " + functionAddress +
                            " has chained unwind info at " + unwindInfoAddress + ". Deleting...");
                        currentProgram.getFunctionManager().removeFunction(func.getEntryPoint());
                    }
                }
            }
            catch (MemoryAccessException e) {
                printerr("Could not read unwind info for function at " + functionAddress +
                    ". Expected to find it at " + unwindInfoAddress + " but failed.");
            }
        }

        if (monitor.isCancelled()) {
            println("\nScript cancelled by user.");
        }
        else {
            println("\nAnalysis finished.");
            println("Found " + chainedCount + " functions with chained unwind info.");
        }
    }
}

```

**Comment by ryanmkurtz** [comment]
Could you please attach the binary that is having the issue?

**Comment by axd1x8a** [comment]
Yes, but I will try replicating it with a smaller binary; this one is over 100 MB, and analyzing it to replicate this would not be worthwhile

**Comment by astrelsky** [comment]
> Could you please attach the binary that is having the issue?

FWIW, I've seen this done intentionally for anti-analysis.

**Comment by axd1x8a** [comment]
> > Could you please attach the binary that is having the issue?
> 
> FWIW, I've seen this done intentionally for anti-analysis.

This may be true, but running this https://github.com/NationalSecurityAgency/ghidra/issues/8459#issuecomment-3216585262 script, fixed all this functions, so I don't think this is the case here

**Comment by astrelsky** [comment]
> > > Could you please attach the binary that is having the issue?
> > 
> > FWIW, I've seen this done intentionally for anti-analysis.
> 
> This may be true, but running this https://github.com/NationalSecurityAgency/ghidra/issues/8459#issuecomment-3216585262 script, fixed all this functions, so I don't think this is the case here

Right. I was just bringing it up so he would be aware of it. It should be resilient and have some kind of way to prevail erroneous function creation if something does seem right about it.

**Comment by ryanmkurtz** [comment]
And you are sure you are running off the latest `patch` branch? Your script is checking for seemingly the exact thing my fix is checking for.

**Comment by axd1x8a** [comment]
Yeah, I tried to replicate the bug again, and I think the problem was that I only analyzed the binary in 11.4.2 -- I imported it in 11.4.1, which is why these functions exist. Sorry for taking your time

**Comment by ryanmkurtz** [comment]
No problem, thanks for putting my mind at ease on this fix.
