### ISSUE TITLE
Decompiling some aarch64 files causes ` Low-level Error: Forced merge caused intersection`

### ISSUE THREAD

**Issue by shamefulCake1** [NationalSecurityAgency/ghidra#8651]
**Describe the bug**
At least one function in at least one aarch64 file refuses decompilation saying ` Low-level Error: Forced merge caused intersection`.
The file is not intentionally obfuscated or created decompiler-resistant.

**To Reproduce**
1. Unzip   [libAlgoInterface.zip](https://github.com/user-attachments/files/23625149/libAlgoInterface.zip) to obtain libAlgoInterface.so
2. Open in Ghidra decompiler
3. Open the function called `rotateMirrorProcess`
4. See error in the decompiler window.

**Expected behavior**
Some sort of reasonable decompilation is produced.

**Screenshots**

<img width="1920" height="986" alt="Image" src="https://github.com/user-attachments/assets/910ef6e3-3db0-4f12-bcd0-1cc408c74d64" />

**Attachments**

None.

**Environment (please complete the following information):**
 - OS: Linux  6.12.16 #1 SMP PREEMPT_DYNAMIC Wed Mar 12 07:54:09 CST 2025 x86_64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz GenuineIntel GNU/Linux
 - Java Version: openjdk version "21.0.4" 2024-07-16 LTS OpenJDK Runtime Environment Zulu21.36+17-CA (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Zulu21.36+17-CA (build 21.0.4+7-LTS, mixed mode, sharing)
 - Ghidra Version: 11.4.2
 - Ghidra Origin: github

**Additional context**
Not really.

**Comment by johnnyserup** [comment]
### ✅ Suggested Change in `Merge::merge` Method
```cpp
bool Merge::merge(HighVariable *high1, HighVariable *high2, bool isspeculative) {
    // If both variables are already the same, nothing to do
    if (high1 == high2) return true;

    // If the intersection test fails, do not merge
    if (testCache.intersection(high1, high2)) return false;

    // New compatibility check before performing the actual merge
    // This prevents merging variables that have overlapping but incompatible ranges
    if (!isCompatible(high1, high2)) {
        warning("Skipped merge due to incompatible ranges");
        return false; // Avoid crash and continue SSA without this merge
    }

    // Perform the actual merge
    high1->merge(high2, &testCache, isspeculative);

    // Update coverage information after merging
    high1->updateCover();

    return true;
}

// Helper function to check compatibility between two HighVariables
bool Merge::isCompatible(HighVariable *hv1, HighVariable *hv2) {
    // If their coverage ranges intersect, they are not compatible
    if (hv1->getCover().intersects(hv2->getCover())) return false;

    // Otherwise, they are safe to merge
    return true;
}
```

---

### **Why this change?**
- Prevents the fatal error **“Forced merge caused intersection”** by skipping merges that would create invalid SSA states.
- Logs a warning instead of crashing, so the user still gets partial decompilation.
- Keeps the merge logic intact for valid cases.

---

**Comment by jobermayr** [comment]
Get it also on x86_64: [issue8651.xml](https://github.com/user-attachments/files/23636198/issue8651.xml)

With [patch](https://github.com/jobermayr/ghidra-staging/blob/master/8651-Decompiling-some-aarch64-files-causes-Low-level.patch) applied:
```
/* WARNING: Skipped merge: !high1->getCover().intersect(high2->getCover())
   high1.getCover():
   0: begin-end
   1: begin-0x0001400016e9:3b0
   
   high2.getCover():
   3: 0x000140001732:2c1-0x00014000173e:3b1
    */
/* WARNING: Skipped merge: !high1->getCover().intersect(high2->getCover())
   high1.getCover():
   0: begin-end
   1: begin-0x0001400016e9:3b0
   
   high2.getCover():
   3: 0x00014000173e:3b1-0x00014000173e:3b1
    */
/* WARNING: Skipped merge: !high1->getCover().intersect(high2->getCover())
   high1.getCover():
   1: 0x0001400016c9:c3-0x0001400016d5:ce
   
   high2.getCover():
   1: 0x0001400016d9:3cf-0x0001400016e5:e5
    */
/* WARNING: Skipped merge: !high1->getCover().intersect(high2->getCover())
   high1.getCover():
   1: 0x0001400016c9:c3-0x0001400016d5:ce
   
   high2.getCover():
   1: 0x0001400016e9:3d0-0x0001400016fe:12e
    */
```

**Comment by shamefulCake1** [comment]
With this patch and ghidra-master, I am getting another error:

```
  Exception while decompiling 00b9d92c: Response buffer size exceeded for: libAlgoInterface.so
```

Is this patch only for 11.4.2?

Just checked, does not actually work for 11.4.2.

UPD:

Ah, sorry, this is me being stupid. I increased buffer size, and it worked, producing a "function' with 6 000 000 + lines of "begin-end" and "begin-begin", and a reasonably-looking function body.

I guess this should be enough for my purposes.
But what are those millions of "begin-end"?

**Comment by shamefulCake1** [comment]
Can this issue be closed, or can I test something for you with respect to this patch?

**Comment by shamefulCake1** [comment]
The patch by @johnnyserup does not seem to apply any more?

Is there anything else to be done about this issue?

**Comment by shamefulCake1** [comment]
Fixed patch for 4e8ff9e621963a3fa739ccef36d68fa140360645

Also requires an increased size of Tool Options -> Decompiler -> Decompiler Max-Payload (MBytes) -> 500, timeout 180

```diff
diff --git a/Ghidra/Features/Decompiler/src/decompile/cpp/merge.cc b/Ghidra/Features/Decompiler/src/decompile/cpp/merge.cc
index c416820055..02664d983f 100644
--- a/Ghidra/Features/Decompiler/src/decompile/cpp/merge.cc
+++ b/Ghidra/Features/Decompiler/src/decompile/cpp/merge.cc
@@ -284,7 +284,7 @@ void Merge::mergeLinear(vector<HighVariable *> &highvec)
     high = *initer;
     for(outiter=highstack.begin();outiter!=highstack.end();++outiter) {
       if (mergeTestSpeculative(*outiter,high))
-	if (merge(*outiter,high,true)) break;
+	if (merge(*outiter,high,true,false)) break;
     }
     if (outiter==highstack.end())
       highstack.push_back(high);
@@ -311,8 +311,7 @@ void Merge::mergeRangeMust(VarnodeLocSet::const_iterator startiter,VarnodeLocSet
     vn = *startiter;
     if (vn->getHigh() == high) continue;
     mergeTestMust(vn);
-    if (!merge(high,vn->getHigh(),false))
-      throw LowlevelError("Forced merge caused intersection");
+    merge(high,vn->getHigh(),false,true);
   }
 }
 
@@ -343,7 +342,7 @@ void Merge::mergeOpcode(OpCode opc)
 	vn2 = op->getIn(j);
 	if (!mergeTestBasic(vn2)) continue;
 	if (mergeTestRequired(vn1->getHigh(),vn2->getHigh()))
-	  merge(vn1->getHigh(),vn2->getHigh(),false);	// This is a required merge
+	  merge(vn1->getHigh(),vn2->getHigh(),false, false);	// This is a required merge
       }
     }
   }
@@ -763,7 +762,7 @@ void Merge::mergeOp(PcodeOp *op)
   for(i=0;i<max;++i) {		// Try to merge everything for real now
     if (!mergeTestRequired(op->getOut()->getHigh(),op->getIn(i)->getHigh()))
       throw LowlevelError("Non-cover related merge restriction violated, despite trims");
-    if (!merge(op->getOut()->getHigh(),op->getIn(i)->getHigh(),false)) {
+    if (!merge(op->getOut()->getHigh(),op->getIn(i)->getHigh(),false, false)) {
       ostringstream errstr;
       errstr << "Unable to force merge of op at " << op->getSeqNum();
       throw LowlevelError(errstr.str());
@@ -854,7 +853,7 @@ void Merge::mergeIndirect(PcodeOp *indop)
 
   Varnode *invn0 = indop->getIn(0);
   if (mergeTestRequired(outvn->getHigh(),invn0->getHigh())) {
-    if (merge(invn0->getHigh(),outvn->getHigh(),false))
+    if (merge(invn0->getHigh(),outvn->getHigh(),false, false))
       return;
   }
   // If we cannot merge, the only thing that can go wrong with an input trim, is if the output of
@@ -862,7 +861,7 @@ void Merge::mergeIndirect(PcodeOp *indop)
   if (snipOutputInterference(indop)) {
     // If we found (and snipped) something related to the output, try merging again before snipping the INDIRECT
     if (mergeTestRequired(outvn->getHigh(), invn0->getHigh())) {
-      if (merge(invn0->getHigh(),outvn->getHigh(),false))
+      if (merge(invn0->getHigh(),outvn->getHigh(),false, false))
 	return;
     }
   }
@@ -876,7 +875,7 @@ void Merge::mergeIndirect(PcodeOp *indop)
   data.opSetInput(indop,newop->getOut(),0);
   data.opInsertBefore(newop,indop);
   if (!mergeTestRequired(outvn->getHigh(),indop->getIn(0)->getHigh()) ||
-      (!merge(indop->getIn(0)->getHigh(),outvn->getHigh(),false))) // Try merge again
+    (!merge(indop->getIn(0)->getHigh(),outvn->getHigh(),false,true))) // Try merge again
     //  if (!merge(indop->Input(0)->High(),outvn->High()))
     throw LowlevelError("Unable to merge address forced indirect");
 }
@@ -939,7 +938,7 @@ void Merge::mergeMultiEntry(void)
 	conflictCount += 1;
 	continue;
       }
-      if (!merge(high,newHigh,false)) {		// Attempt the merge
+      if (!merge(high,newHigh,false, true)) {		// Attempt the merge
 	symbol->setMergeProblems();
 	newHigh->setUnmerged();
 	conflictCount += 1;
@@ -1007,7 +1006,7 @@ void Merge::mergeAdjacent(void)
       if (!mergeTestAdjacent(high_out,high_in)) continue;
 
       if (!testCache.intersection(high_in,high_out)) // If no interval intersection
-	merge(high_out,high_in,true);
+	merge(high_out,high_in,true, false);
     }
   }
 }
@@ -1561,12 +1560,33 @@ void Merge::registerProtoPartialRoot(Varnode *vn)
 /// \param high1 is the first HighVariable being merged
 /// \param high2 is the second
 /// \param isspeculative is \b true if the desired merge is speculative
+/// \param printWarning is \b true if decompiler should inform about issues while merging
 /// \return \b true if the merge was successful
-bool Merge::merge(HighVariable *high1,HighVariable *high2,bool isspeculative)
+bool Merge::merge(HighVariable *high1,HighVariable *high2,bool isspeculative,bool printWarning)
 
 {
+  ostringstream info, s1, s2;
   if (high1 == high2) return true; // Already merged
-  if (testCache.intersection(high1,high2)) return false;
+  if (testCache.intersection(high1,high2)) {
+    if (printWarning) {
+      high1->printInfo(s1);
+      high2->printInfo(s2);
+      info << "Skipped merge: testCache.intersection(high1,high2)\nhigh1:\n" << s1.str() << "\nhigh2:\n" << s2.str();
+      data.warningHeader(info.str());
+    }
+    return false;
+  }
+
+  // If their coverage ranges intersect, they are not compatible
+  if (!high1->getCover().intersect(high2->getCover())) {
+    if (printWarning) {
+      high1->getCover().print(s1);
+      high2->getCover().print(s2);
+      info << "Skipped merge: !high1->getCover().intersect(high2->getCover())\nhigh1.getCover():\n" << s1.str() << "\nhigh2.getCover():\n" << s2.str();
+      data.warningHeader(info.str());
+    }
+    return false;
+  }
 
   high1->merge(high2,&testCache,isspeculative);	// Do the actual merge
   high1->updateCover();				// Update cover now so that updateHigh won't purge cached tests
diff --git a/Ghidra/Features/Decompiler/src/decompile/cpp/merge.hh b/Ghidra/Features/Decompiler/src/decompile/cpp/merge.hh
index 4ff5c24802..3596ec4291 100644
--- a/Ghidra/Features/Decompiler/src/decompile/cpp/merge.hh
+++ b/Ghidra/Features/Decompiler/src/decompile/cpp/merge.hh
@@ -108,7 +108,7 @@ class Merge {
   void mergeOp(PcodeOp *op);
   void mergeIndirect(PcodeOp *indop);
   void mergeLinear(vector<HighVariable *> &highvec);
-  bool merge(HighVariable *high1,HighVariable *high2,bool isspeculative);
+  bool merge(HighVariable *high1,HighVariable *high2,bool isspeculative, bool printWarning);
   bool checkCopyPair(HighVariable *high,PcodeOp *domOp,PcodeOp *subOp);
   void buildDominantCopy(HighVariable *high,vector<PcodeOp *> &copy,int4 pos,int4 size);
   void markRedundantCopies(HighVariable *high,vector<PcodeOp *> &copy,int4 pos,int4 size);
```

**Comment by ryanmkurtz** [comment]
I confirm this is still an issue in the `master` branch.  Will poke @caheckman about it.

**Comment by shamefulCake1** [comment]
This is amazing, thank you. Things are decompiled where I need them, and decompiling is also seemingly faster.
